package database

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"fmt"
	"time"
)

const rollbackTimeout = 2 * time.Second

// contextDBTX matches the interface generated by sqlc. Keep this assertion
// local so database/sql remains the only persistence API exposed here.
type contextDBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

var (
	_ contextDBTX = (*Database)(nil)
	_ contextDBTX = (*ReadTx)(nil)
	_ contextDBTX = (*WriteTx)(nil)
)

// ReadTx is the context-aware SQL surface available during Database.Read.
// Database.Read additionally enables SQLite's query_only guard for the
// dedicated connection so statements cannot mutate through query-returning
// SQL or prepared statements.
type ReadTx struct {
	tx *sql.Tx
}

func (tx *ReadTx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	return tx.tx.ExecContext(ctx, query, args...)
}

func (tx *ReadTx) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	return tx.tx.PrepareContext(ctx, query)
}

func (tx *ReadTx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	return tx.tx.QueryContext(ctx, query, args...)
}

func (tx *ReadTx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return tx.tx.QueryRowContext(ctx, query, args...)
}

// Read runs operation against one SQLite read snapshot on a dedicated
// connection. The transaction is committed only after the callback succeeds
// and the caller context remains valid.
func (d *Database) Read(ctx context.Context, operation func(*ReadTx) error) (resultErr error) {
	if operation == nil {
		return errors.New("database read operation is nil")
	}

	conn, err := d.conn.Conn(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = conn.Close() }()

	if _, err := conn.ExecContext(ctx, "PRAGMA query_only = ON"); err != nil {
		return fmt.Errorf("enable read-only connection: %w", err)
	}
	defer func() {
		if err := restoreWritableConnection(conn); err != nil {
			resultErr = errors.Join(resultErr, err)
		}
	}()

	tx, err := conn.BeginTx(ctx, &sql.TxOptions{ReadOnly: true})
	if err != nil {
		return fmt.Errorf("begin read transaction: %w", err)
	}
	completed := false
	defer func() {
		if !completed {
			_ = tx.Rollback()
		}
	}()

	if err := operation(&ReadTx{tx: tx}); err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit read transaction: %w", err)
	}
	completed = true
	return nil
}

// WriteTx is the context-aware SQL surface available during Database.Write.
// It deliberately does not expose the dedicated *sql.Conn or transaction
// lifecycle statements.
type WriteTx struct {
	conn *sql.Conn
}

func (tx *WriteTx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	return tx.conn.ExecContext(ctx, query, args...)
}

func (tx *WriteTx) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	return tx.conn.PrepareContext(ctx, query)
}

func (tx *WriteTx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	return tx.conn.QueryContext(ctx, query, args...)
}

func (tx *WriteTx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	return tx.conn.QueryRowContext(ctx, query, args...)
}

// Write runs operation in one serialized SQLite write transaction. It never
// retries: callers receive lock, context, callback, or commit failures as-is.
func (d *Database) Write(ctx context.Context, operation func(*WriteTx) error) error {
	if operation == nil {
		return errors.New("database write operation is nil")
	}

	conn, err := d.conn.Conn(ctx)
	if err != nil {
		return err
	}
	defer conn.Close()

	if _, err := conn.ExecContext(ctx, "BEGIN IMMEDIATE"); err != nil {
		return fmt.Errorf("begin immediate transaction: %w", err)
	}

	committed := false
	defer func() {
		if !committed {
			rollbackWithFreshContext(conn)
		}
		if recovered := recover(); recovered != nil {
			panic(recovered)
		}
	}()

	if err := operation(&WriteTx{conn: conn}); err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if _, err := conn.ExecContext(ctx, "COMMIT"); err != nil {
		return fmt.Errorf("commit write transaction: %w", err)
	}
	committed = true
	return nil
}

func rollbackWithFreshContext(conn *sql.Conn) {
	ctx, cancel := context.WithTimeout(context.Background(), rollbackTimeout)
	defer cancel()
	_, _ = conn.ExecContext(ctx, "ROLLBACK")
}

func restoreWritableConnection(conn *sql.Conn) error {
	ctx, cancel := context.WithTimeout(context.Background(), rollbackTimeout)
	defer cancel()
	if _, err := conn.ExecContext(ctx, "PRAGMA query_only = OFF"); err != nil {
		// A pooled connection must never remain accidentally read-only. Returning
		// driver.ErrBadConn from Raw makes database/sql discard the physical
		// connection instead of putting it back in the pool.
		_ = conn.Raw(func(any) error { return driver.ErrBadConn })
		return fmt.Errorf("restore writable connection: %w", err)
	}
	return nil
}
