// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveItem = `-- name: ArchiveItem :execrows
UPDATE items
SET
    archived_at_ms = CAST(?1 AS INTEGER),
    updated_at_ms = ?2
WHERE id = ?3
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?4
`

type ArchiveItemParams struct {
	ArchivedAtMs        int64
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) ArchiveItem(ctx context.Context, arg ArchiveItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveItem,
		arg.ArchivedAtMs,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const archiveItemPackaging = `-- name: ArchiveItemPackaging :execrows
UPDATE item_packagings
SET
    archived_at_ms = CAST(?1 AS INTEGER),
    updated_at_ms = ?2
WHERE id = ?3
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?4
`

type ArchiveItemPackagingParams struct {
	ArchivedAtMs        int64
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) ArchiveItemPackaging(ctx context.Context, arg ArchiveItemPackagingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveItemPackaging,
		arg.ArchivedAtMs,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getItem = `-- name: GetItem :one
SELECT
    id,
    name,
    normalized_name,
    sku,
    normalized_sku,
    description,
    base_unit_code,
    is_purchasable,
    is_producible,
    is_sellable,
    default_sale_price_minor,
    reorder_quantity_atomic,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
FROM items
WHERE id = ?1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.SKU,
		&i.NormalizedSKU,
		&i.Description,
		&i.BaseUnitCode,
		&i.IsPurchasable,
		&i.IsProducible,
		&i.IsSellable,
		&i.DefaultSalePriceMinor,
		&i.ReorderQuantityAtomic,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ArchivedAtMs,
	)
	return i, err
}

const getItemPackaging = `-- name: GetItemPackaging :one
SELECT
    id,
    item_id,
    name,
    normalized_name,
    entered_unit_code,
    conversion_numerator_atomic,
    conversion_denominator,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
FROM item_packagings
WHERE id = ?1
`

func (q *Queries) GetItemPackaging(ctx context.Context, id int64) (ItemPackaging, error) {
	row := q.db.QueryRowContext(ctx, getItemPackaging, id)
	var i ItemPackaging
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.NormalizedName,
		&i.EnteredUnitCode,
		&i.ConversionNumeratorAtomic,
		&i.ConversionDenominator,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ArchivedAtMs,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (
    name,
    normalized_name,
    sku,
    normalized_sku,
    description,
    base_unit_code,
    is_purchasable,
    is_producible,
    is_sellable,
    default_sale_price_minor,
    reorder_quantity_atomic,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    NULL
)
RETURNING id
`

type InsertItemParams struct {
	Name                  string
	NormalizedName        string
	SKU                   sql.NullString
	NormalizedSKU         sql.NullString
	Description           sql.NullString
	BaseUnitCode          string
	IsPurchasable         int64
	IsProducible          int64
	IsSellable            int64
	DefaultSalePriceMinor sql.NullInt64
	ReorderQuantityAtomic sql.NullInt64
	CreatedAtMs           int64
	UpdatedAtMs           int64
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertItem,
		arg.Name,
		arg.NormalizedName,
		arg.SKU,
		arg.NormalizedSKU,
		arg.Description,
		arg.BaseUnitCode,
		arg.IsPurchasable,
		arg.IsProducible,
		arg.IsSellable,
		arg.DefaultSalePriceMinor,
		arg.ReorderQuantityAtomic,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertItemPackaging = `-- name: InsertItemPackaging :one
INSERT INTO item_packagings (
    item_id,
    name,
    normalized_name,
    entered_unit_code,
    conversion_numerator_atomic,
    conversion_denominator,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    NULL
)
RETURNING id
`

type InsertItemPackagingParams struct {
	ItemID                    int64
	Name                      string
	NormalizedName            string
	EnteredUnitCode           string
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	CreatedAtMs               int64
	UpdatedAtMs               int64
}

func (q *Queries) InsertItemPackaging(ctx context.Context, arg InsertItemPackagingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertItemPackaging,
		arg.ItemID,
		arg.Name,
		arg.NormalizedName,
		arg.EnteredUnitCode,
		arg.ConversionNumeratorAtomic,
		arg.ConversionDenominator,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listItemPackagings = `-- name: ListItemPackagings :many
SELECT
    id,
    item_id,
    name,
    normalized_name,
    entered_unit_code,
    conversion_numerator_atomic,
    conversion_denominator,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
FROM item_packagings
WHERE item_id = ?1
  AND (CAST(?2 AS INTEGER) = 1 OR archived_at_ms IS NULL)
ORDER BY normalized_name, id
`

type ListItemPackagingsParams struct {
	ItemID          int64
	IncludeArchived int64
}

func (q *Queries) ListItemPackagings(ctx context.Context, arg ListItemPackagingsParams) ([]ItemPackaging, error) {
	rows, err := q.db.QueryContext(ctx, listItemPackagings, arg.ItemID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemPackaging{}
	for rows.Next() {
		var i ItemPackaging
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.NormalizedName,
			&i.EnteredUnitCode,
			&i.ConversionNumeratorAtomic,
			&i.ConversionDenominator,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.ArchivedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT
    id,
    name,
    normalized_name,
    sku,
    normalized_sku,
    description,
    base_unit_code,
    is_purchasable,
    is_producible,
    is_sellable,
    default_sale_price_minor,
    reorder_quantity_atomic,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
FROM items
WHERE
    (
        CAST(?1 AS INTEGER) = 2
        OR (CAST(?1 AS INTEGER) = 0 AND archived_at_ms IS NULL)
        OR (CAST(?1 AS INTEGER) = 1 AND archived_at_ms IS NOT NULL)
    )
    AND (CAST(?2 AS INTEGER) = 0 OR is_purchasable = 1)
    AND (CAST(?3 AS INTEGER) = 0 OR is_producible = 1)
    AND (CAST(?4 AS INTEGER) = 0 OR is_sellable = 1)
    AND (
        CAST(?5 AS TEXT) = ''
        OR instr(normalized_name, CAST(?5 AS TEXT)) > 0
        OR instr(COALESCE(normalized_sku, ''), CAST(?5 AS TEXT)) > 0
    )
    AND (
        CAST(?6 AS TEXT) = ''
        OR normalized_name > CAST(?6 AS TEXT)
        OR (
            normalized_name = CAST(?6 AS TEXT)
            AND id > ?7
        )
    )
ORDER BY normalized_name, id
LIMIT ?8
`

type ListItemsParams struct {
	ArchiveFilter       int64
	RequirePurchasable  int64
	RequireProducible   int64
	RequireSellable     int64
	SearchKey           string
	AfterNormalizedName string
	AfterID             int64
	LimitCount          int64
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems,
		arg.ArchiveFilter,
		arg.RequirePurchasable,
		arg.RequireProducible,
		arg.RequireSellable,
		arg.SearchKey,
		arg.AfterNormalizedName,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.SKU,
			&i.NormalizedSKU,
			&i.Description,
			&i.BaseUnitCode,
			&i.IsPurchasable,
			&i.IsProducible,
			&i.IsSellable,
			&i.DefaultSalePriceMinor,
			&i.ReorderQuantityAtomic,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.ArchivedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconfigureArchivedItemPackaging = `-- name: ReconfigureArchivedItemPackaging :execrows
UPDATE item_packagings
SET
    name = ?1,
    normalized_name = ?2,
    entered_unit_code = ?3,
    conversion_numerator_atomic = ?4,
    conversion_denominator = ?5,
    updated_at_ms = ?6,
    archived_at_ms = ?6
WHERE id = ?7
  AND archived_at_ms IS NOT NULL
  AND updated_at_ms = ?8
`

type ReconfigureArchivedItemPackagingParams struct {
	Name                      string
	NormalizedName            string
	EnteredUnitCode           string
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	UpdatedAtMs               int64
	ID                        int64
	ExpectedUpdatedAtMs       int64
}

func (q *Queries) ReconfigureArchivedItemPackaging(ctx context.Context, arg ReconfigureArchivedItemPackagingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconfigureArchivedItemPackaging,
		arg.Name,
		arg.NormalizedName,
		arg.EnteredUnitCode,
		arg.ConversionNumeratorAtomic,
		arg.ConversionDenominator,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreItem = `-- name: RestoreItem :execrows
UPDATE items
SET
    archived_at_ms = NULL,
    updated_at_ms = ?1
WHERE id = ?2
  AND archived_at_ms IS NOT NULL
  AND updated_at_ms = ?3
`

type RestoreItemParams struct {
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) RestoreItem(ctx context.Context, arg RestoreItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreItem, arg.UpdatedAtMs, arg.ID, arg.ExpectedUpdatedAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreItemPackaging = `-- name: RestoreItemPackaging :execrows
UPDATE item_packagings
SET
    archived_at_ms = NULL,
    updated_at_ms = ?1
WHERE id = ?2
  AND archived_at_ms IS NOT NULL
  AND updated_at_ms = ?3
`

type RestoreItemPackagingParams struct {
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) RestoreItemPackaging(ctx context.Context, arg RestoreItemPackagingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreItemPackaging, arg.UpdatedAtMs, arg.ID, arg.ExpectedUpdatedAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItem = `-- name: UpdateItem :execrows
UPDATE items
SET
    name = ?1,
    normalized_name = ?2,
    sku = ?3,
    normalized_sku = ?4,
    description = ?5,
    base_unit_code = ?6,
    is_purchasable = ?7,
    is_producible = ?8,
    is_sellable = ?9,
    default_sale_price_minor = ?10,
    reorder_quantity_atomic = ?11,
    updated_at_ms = ?12
WHERE id = ?13
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?14
`

type UpdateItemParams struct {
	Name                  string
	NormalizedName        string
	SKU                   sql.NullString
	NormalizedSKU         sql.NullString
	Description           sql.NullString
	BaseUnitCode          string
	IsPurchasable         int64
	IsProducible          int64
	IsSellable            int64
	DefaultSalePriceMinor sql.NullInt64
	ReorderQuantityAtomic sql.NullInt64
	UpdatedAtMs           int64
	ID                    int64
	ExpectedUpdatedAtMs   int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItem,
		arg.Name,
		arg.NormalizedName,
		arg.SKU,
		arg.NormalizedSKU,
		arg.Description,
		arg.BaseUnitCode,
		arg.IsPurchasable,
		arg.IsProducible,
		arg.IsSellable,
		arg.DefaultSalePriceMinor,
		arg.ReorderQuantityAtomic,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateItemPackaging = `-- name: UpdateItemPackaging :execrows
UPDATE item_packagings
SET
    name = ?1,
    normalized_name = ?2,
    entered_unit_code = ?3,
    conversion_numerator_atomic = ?4,
    conversion_denominator = ?5,
    updated_at_ms = ?6
WHERE id = ?7
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?8
`

type UpdateItemPackagingParams struct {
	Name                      string
	NormalizedName            string
	EnteredUnitCode           string
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	UpdatedAtMs               int64
	ID                        int64
	ExpectedUpdatedAtMs       int64
}

func (q *Queries) UpdateItemPackaging(ctx context.Context, arg UpdateItemPackagingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItemPackaging,
		arg.Name,
		arg.NormalizedName,
		arg.EnteredUnitCode,
		arg.ConversionNumeratorAtomic,
		arg.ConversionDenominator,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
