// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counterparties.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveCounterparty = `-- name: ArchiveCounterparty :execrows
UPDATE counterparties
SET
    archived_at_ms = CAST(?1 AS INTEGER),
    updated_at_ms = ?2
WHERE id = ?3
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?4
`

type ArchiveCounterpartyParams struct {
	ArchivedAtMs        int64
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) ArchiveCounterparty(ctx context.Context, arg ArchiveCounterpartyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveCounterparty,
		arg.ArchivedAtMs,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCounterpartyRoles = `-- name: DeleteCounterpartyRoles :execrows
DELETE FROM counterparty_roles
WHERE counterparty_id = ?1
`

func (q *Queries) DeleteCounterpartyRoles(ctx context.Context, counterpartyID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCounterpartyRoles, counterpartyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCounterparty = `-- name: GetCounterparty :one
SELECT
    counterparty.id,
    counterparty.name,
    counterparty.phone,
    counterparty.email,
    counterparty.notes,
    counterparty.created_at_ms,
    counterparty.updated_at_ms,
    counterparty.archived_at_ms,
    CAST(COALESCE((
        SELECT role.created_at_ms
        FROM counterparty_roles role
        WHERE role.counterparty_id = counterparty.id
          AND role.role = 'SUPPLIER'
    ), -1) AS INTEGER) AS supplier_role_created_at_ms,
    CAST(COALESCE((
        SELECT role.created_at_ms
        FROM counterparty_roles role
        WHERE role.counterparty_id = counterparty.id
          AND role.role = 'CUSTOMER'
    ), -1) AS INTEGER) AS customer_role_created_at_ms
FROM counterparties counterparty
WHERE counterparty.id = ?1
`

type GetCounterpartyRow struct {
	ID                      int64
	Name                    string
	Phone                   sql.NullString
	Email                   sql.NullString
	Notes                   sql.NullString
	CreatedAtMs             int64
	UpdatedAtMs             int64
	ArchivedAtMs            sql.NullInt64
	SupplierRoleCreatedAtMs int64
	CustomerRoleCreatedAtMs int64
}

func (q *Queries) GetCounterparty(ctx context.Context, id int64) (GetCounterpartyRow, error) {
	row := q.db.QueryRowContext(ctx, getCounterparty, id)
	var i GetCounterpartyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ArchivedAtMs,
		&i.SupplierRoleCreatedAtMs,
		&i.CustomerRoleCreatedAtMs,
	)
	return i, err
}

const insertCounterparty = `-- name: InsertCounterparty :one
INSERT INTO counterparties (
    name,
    phone,
    email,
    notes,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    NULL
)
RETURNING id
`

type InsertCounterpartyParams struct {
	Name        string
	Phone       sql.NullString
	Email       sql.NullString
	Notes       sql.NullString
	CreatedAtMs int64
	UpdatedAtMs int64
}

func (q *Queries) InsertCounterparty(ctx context.Context, arg InsertCounterpartyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertCounterparty,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCounterpartyRole = `-- name: InsertCounterpartyRole :exec
INSERT INTO counterparty_roles (
    counterparty_id,
    role,
    created_at_ms
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type InsertCounterpartyRoleParams struct {
	CounterpartyID int64
	Role           string
	CreatedAtMs    int64
}

func (q *Queries) InsertCounterpartyRole(ctx context.Context, arg InsertCounterpartyRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertCounterpartyRole, arg.CounterpartyID, arg.Role, arg.CreatedAtMs)
	return err
}

const listCounterparties = `-- name: ListCounterparties :many
SELECT
    counterparty.id,
    counterparty.name,
    counterparty.phone,
    counterparty.email,
    counterparty.notes,
    counterparty.created_at_ms,
    counterparty.updated_at_ms,
    counterparty.archived_at_ms,
    CAST(COALESCE((
        SELECT role.created_at_ms
        FROM counterparty_roles role
        WHERE role.counterparty_id = counterparty.id
          AND role.role = 'SUPPLIER'
    ), -1) AS INTEGER) AS supplier_role_created_at_ms,
    CAST(COALESCE((
        SELECT role.created_at_ms
        FROM counterparty_roles role
        WHERE role.counterparty_id = counterparty.id
          AND role.role = 'CUSTOMER'
    ), -1) AS INTEGER) AS customer_role_created_at_ms
FROM counterparties counterparty
WHERE
    (
        CAST(?1 AS INTEGER) = 2
        OR (CAST(?1 AS INTEGER) = 0 AND counterparty.archived_at_ms IS NULL)
        OR (CAST(?1 AS INTEGER) = 1 AND counterparty.archived_at_ms IS NOT NULL)
    )
    AND (
        CAST(?2 AS TEXT) = ''
        OR EXISTS (
            SELECT 1
            FROM counterparty_roles role
            WHERE role.counterparty_id = counterparty.id
              AND role.role = CAST(?2 AS TEXT)
        )
    )
    -- Counterparty names intentionally have display-text, case-sensitive search.
    AND (
        CAST(?3 AS TEXT) = ''
        OR instr(counterparty.name, CAST(?3 AS TEXT)) > 0
    )
    AND (
        CAST(?4 AS TEXT) = ''
        OR counterparty.name > CAST(?4 AS TEXT)
        OR (
            counterparty.name = CAST(?4 AS TEXT)
            AND counterparty.id > ?5
        )
    )
ORDER BY counterparty.name, counterparty.id
LIMIT ?6
`

type ListCounterpartiesParams struct {
	ArchiveFilter int64
	RoleFilter    string
	SearchText    string
	AfterName     string
	AfterID       int64
	LimitCount    int64
}

type ListCounterpartiesRow struct {
	ID                      int64
	Name                    string
	Phone                   sql.NullString
	Email                   sql.NullString
	Notes                   sql.NullString
	CreatedAtMs             int64
	UpdatedAtMs             int64
	ArchivedAtMs            sql.NullInt64
	SupplierRoleCreatedAtMs int64
	CustomerRoleCreatedAtMs int64
}

func (q *Queries) ListCounterparties(ctx context.Context, arg ListCounterpartiesParams) ([]ListCounterpartiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCounterparties,
		arg.ArchiveFilter,
		arg.RoleFilter,
		arg.SearchText,
		arg.AfterName,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCounterpartiesRow{}
	for rows.Next() {
		var i ListCounterpartiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Notes,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.ArchivedAtMs,
			&i.SupplierRoleCreatedAtMs,
			&i.CustomerRoleCreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterpartyRoles = `-- name: ListCounterpartyRoles :many
SELECT
    counterparty_id,
    role,
    created_at_ms
FROM counterparty_roles
WHERE counterparty_id = ?1
ORDER BY role
`

func (q *Queries) ListCounterpartyRoles(ctx context.Context, counterpartyID int64) ([]CounterpartyRole, error) {
	rows, err := q.db.QueryContext(ctx, listCounterpartyRoles, counterpartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CounterpartyRole{}
	for rows.Next() {
		var i CounterpartyRole
		if err := rows.Scan(&i.CounterpartyID, &i.Role, &i.CreatedAtMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCounterparty = `-- name: RestoreCounterparty :execrows
UPDATE counterparties
SET
    archived_at_ms = NULL,
    updated_at_ms = ?1
WHERE id = ?2
  AND archived_at_ms IS NOT NULL
  AND updated_at_ms = ?3
`

type RestoreCounterpartyParams struct {
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) RestoreCounterparty(ctx context.Context, arg RestoreCounterpartyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreCounterparty, arg.UpdatedAtMs, arg.ID, arg.ExpectedUpdatedAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCounterparty = `-- name: UpdateCounterparty :execrows
UPDATE counterparties
SET
    name = ?1,
    phone = ?2,
    email = ?3,
    notes = ?4,
    updated_at_ms = ?5
WHERE id = ?6
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?7
`

type UpdateCounterpartyParams struct {
	Name                string
	Phone               sql.NullString
	Email               sql.NullString
	Notes               sql.NullString
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) UpdateCounterparty(ctx context.Context, arg UpdateCounterpartyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCounterparty,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
