// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getInventoryBalance = `-- name: GetInventoryBalance :one
SELECT
    balance.item_id,
    item.name AS item_name,
    item.normalized_name AS item_normalized_name,
    item.base_unit_code,
    item.archived_at_ms AS item_archived_at_ms,
    balance.quantity_atomic,
    balance.inventory_value_micro,
    balance.last_document_id,
    balance.updated_at_ms
FROM inventory_balances balance
JOIN items item ON item.id = balance.item_id
WHERE balance.item_id = ?1
`

type GetInventoryBalanceRow struct {
	ItemID              int64
	ItemName            string
	ItemNormalizedName  string
	BaseUnitCode        string
	ItemArchivedAtMs    sql.NullInt64
	QuantityAtomic      int64
	InventoryValueMicro int64
	LastDocumentID      sql.NullInt64
	UpdatedAtMs         int64
}

func (q *Queries) GetInventoryBalance(ctx context.Context, itemID int64) (GetInventoryBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getInventoryBalance, itemID)
	var i GetInventoryBalanceRow
	err := row.Scan(
		&i.ItemID,
		&i.ItemName,
		&i.ItemNormalizedName,
		&i.BaseUnitCode,
		&i.ItemArchivedAtMs,
		&i.QuantityAtomic,
		&i.InventoryValueMicro,
		&i.LastDocumentID,
		&i.UpdatedAtMs,
	)
	return i, err
}

const listEligibleFEFOLots = `-- name: ListEligibleFEFOLots :many
WITH lot_facts AS (
    SELECT
        lot.id,
        lot.item_id,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.originated_on,
        lot.expires_on,
        lot.created_at_ms,
        source_document.id AS source_document_id,
        source_document.kind AS source_document_kind,
        source_document.posting_sequence AS source_posting_sequence,
        source_document.occurred_on AS source_occurred_on,
        CAST(COALESCE(SUM(
            CASE WHEN allocation.restores_allocation_id IS NULL
                THEN allocation.quantity_atomic ELSE 0 END
        ), 0) AS INTEGER) AS consumed_quantity_atomic,
        CAST(COALESCE(SUM(
            CASE WHEN allocation.restores_allocation_id IS NOT NULL
                THEN allocation.quantity_atomic ELSE 0 END
        ), 0) AS INTEGER) AS restored_quantity_atomic,
        lot.initial_quantity_atomic
            - COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0)
            + COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NOT NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0) AS remaining_quantity_atomic
    FROM inventory_lots lot
    JOIN stock_document_lines source_line ON source_line.id = lot.source_line_id
    JOIN stock_documents source_document ON source_document.id = source_line.document_id
    LEFT JOIN lot_allocations allocation ON allocation.lot_id = lot.id
    WHERE lot.item_id = ?2
    GROUP BY
        lot.id,
        lot.item_id,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.originated_on,
        lot.expires_on,
        lot.created_at_ms,
        source_document.id,
        source_document.kind,
        source_document.posting_sequence,
        source_document.occurred_on
)
SELECT
    id,
    item_id,
    source_line_id,
    initial_quantity_atomic,
    consumed_quantity_atomic,
    restored_quantity_atomic,
    remaining_quantity_atomic,
    lot_code,
    originated_on,
    expires_on,
    created_at_ms,
    source_document_id,
    source_document_kind,
    source_posting_sequence,
    source_occurred_on
FROM lot_facts
WHERE remaining_quantity_atomic > 0
  AND (expires_on IS NULL OR expires_on >= CAST(?1 AS TEXT))
ORDER BY
    expires_on IS NULL,
    expires_on,
    source_posting_sequence,
    id
`

type ListEligibleFEFOLotsParams struct {
	BusinessDate string
	ItemID       int64
}

type ListEligibleFEFOLotsRow struct {
	ID                      int64
	ItemID                  int64
	SourceLineID            int64
	InitialQuantityAtomic   int64
	ConsumedQuantityAtomic  int64
	RestoredQuantityAtomic  int64
	RemainingQuantityAtomic int64
	LotCode                 sql.NullString
	OriginatedOn            string
	ExpiresOn               sql.NullString
	CreatedAtMs             int64
	SourceDocumentID        int64
	SourceDocumentKind      string
	SourcePostingSequence   int64
	SourceOccurredOn        string
}

func (q *Queries) ListEligibleFEFOLots(ctx context.Context, arg ListEligibleFEFOLotsParams) ([]ListEligibleFEFOLotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleFEFOLots, arg.BusinessDate, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEligibleFEFOLotsRow{}
	for rows.Next() {
		var i ListEligibleFEFOLotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SourceLineID,
			&i.InitialQuantityAtomic,
			&i.ConsumedQuantityAtomic,
			&i.RestoredQuantityAtomic,
			&i.RemainingQuantityAtomic,
			&i.LotCode,
			&i.OriginatedOn,
			&i.ExpiresOn,
			&i.CreatedAtMs,
			&i.SourceDocumentID,
			&i.SourceDocumentKind,
			&i.SourcePostingSequence,
			&i.SourceOccurredOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryBalances = `-- name: ListInventoryBalances :many
SELECT
    balance.item_id,
    item.name AS item_name,
    item.normalized_name AS item_normalized_name,
    item.base_unit_code,
    item.is_purchasable,
    item.is_producible,
    item.is_sellable,
    item.reorder_quantity_atomic,
    item.archived_at_ms AS item_archived_at_ms,
    balance.quantity_atomic,
    balance.inventory_value_micro,
    balance.last_document_id,
    balance.updated_at_ms
FROM inventory_balances balance
JOIN items item ON item.id = balance.item_id
WHERE
    (CAST(?1 AS INTEGER) = 1 OR item.archived_at_ms IS NULL)
    AND (
        CAST(?2 AS TEXT) = ''
        OR instr(item.normalized_name, CAST(?2 AS TEXT)) > 0
    )
    AND (
        CAST(?3 AS TEXT) = ''
        OR item.normalized_name > CAST(?3 AS TEXT)
        OR (
            item.normalized_name = CAST(?3 AS TEXT)
            AND item.id > ?4
        )
    )
ORDER BY item.normalized_name, item.id
LIMIT ?5
`

type ListInventoryBalancesParams struct {
	IncludeArchived     int64
	SearchKey           string
	AfterNormalizedName string
	AfterItemID         int64
	LimitCount          int64
}

type ListInventoryBalancesRow struct {
	ItemID                int64
	ItemName              string
	ItemNormalizedName    string
	BaseUnitCode          string
	IsPurchasable         int64
	IsProducible          int64
	IsSellable            int64
	ReorderQuantityAtomic sql.NullInt64
	ItemArchivedAtMs      sql.NullInt64
	QuantityAtomic        int64
	InventoryValueMicro   int64
	LastDocumentID        sql.NullInt64
	UpdatedAtMs           int64
}

func (q *Queries) ListInventoryBalances(ctx context.Context, arg ListInventoryBalancesParams) ([]ListInventoryBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryBalances,
		arg.IncludeArchived,
		arg.SearchKey,
		arg.AfterNormalizedName,
		arg.AfterItemID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryBalancesRow{}
	for rows.Next() {
		var i ListInventoryBalancesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.ItemNormalizedName,
			&i.BaseUnitCode,
			&i.IsPurchasable,
			&i.IsProducible,
			&i.IsSellable,
			&i.ReorderQuantityAtomic,
			&i.ItemArchivedAtMs,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
			&i.LastDocumentID,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemLedgerPage = `-- name: ListItemLedgerPage :many
SELECT
    line.id AS line_id,
    line.document_id,
    line.line_order,
    line.item_id,
    line.direction,
    line.quantity_atomic,
    line.entered_unit_code,
    line.entered_packaging_name,
    line.conversion_numerator_atomic,
    line.conversion_denominator,
    line.inventory_value_micro,
    line.commercial_total_minor,
    line.reverses_line_id,
    document.kind AS document_kind,
    document.idempotency_key,
    document.posting_sequence,
    document.counterparty_id,
    counterparty.name AS counterparty_name,
    document.occurred_on,
    document.posted_at_ms,
    document.currency_code,
    document.currency_minor_digits,
    document.reason_code,
    document.notes,
    document.reverses_document_id
FROM stock_document_lines line
JOIN stock_documents document ON document.id = line.document_id
LEFT JOIN counterparties counterparty ON counterparty.id = document.counterparty_id
WHERE line.item_id = ?1
  AND (
      CAST(?2 AS INTEGER) = 0
      OR document.posting_sequence < CAST(?2 AS INTEGER)
      OR (
          document.posting_sequence = CAST(?2 AS INTEGER)
          AND line.line_order > ?3
      )
      OR (
          document.posting_sequence = CAST(?2 AS INTEGER)
          AND line.line_order = ?3
          AND line.id > ?4
      )
  )
ORDER BY document.posting_sequence DESC, line.line_order, line.id
LIMIT ?5
`

type ListItemLedgerPageParams struct {
	ItemID                int64
	BeforePostingSequence int64
	AfterLineOrder        int64
	AfterLineID           int64
	LimitCount            int64
}

type ListItemLedgerPageRow struct {
	LineID                    int64
	DocumentID                int64
	LineOrder                 int64
	ItemID                    int64
	Direction                 string
	QuantityAtomic            int64
	EnteredUnitCode           string
	EnteredPackagingName      sql.NullString
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	InventoryValueMicro       int64
	CommercialTotalMinor      sql.NullInt64
	ReversesLineID            sql.NullInt64
	DocumentKind              string
	IdempotencyKey            string
	PostingSequence           int64
	CounterpartyID            sql.NullInt64
	CounterpartyName          sql.NullString
	OccurredOn                string
	PostedAtMs                int64
	CurrencyCode              string
	CurrencyMinorDigits       int64
	ReasonCode                sql.NullString
	Notes                     sql.NullString
	ReversesDocumentID        sql.NullInt64
}

func (q *Queries) ListItemLedgerPage(ctx context.Context, arg ListItemLedgerPageParams) ([]ListItemLedgerPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemLedgerPage,
		arg.ItemID,
		arg.BeforePostingSequence,
		arg.AfterLineOrder,
		arg.AfterLineID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemLedgerPageRow{}
	for rows.Next() {
		var i ListItemLedgerPageRow
		if err := rows.Scan(
			&i.LineID,
			&i.DocumentID,
			&i.LineOrder,
			&i.ItemID,
			&i.Direction,
			&i.QuantityAtomic,
			&i.EnteredUnitCode,
			&i.EnteredPackagingName,
			&i.ConversionNumeratorAtomic,
			&i.ConversionDenominator,
			&i.InventoryValueMicro,
			&i.CommercialTotalMinor,
			&i.ReversesLineID,
			&i.DocumentKind,
			&i.IdempotencyKey,
			&i.PostingSequence,
			&i.CounterpartyID,
			&i.CounterpartyName,
			&i.OccurredOn,
			&i.PostedAtMs,
			&i.CurrencyCode,
			&i.CurrencyMinorDigits,
			&i.ReasonCode,
			&i.Notes,
			&i.ReversesDocumentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemLotFacts = `-- name: ListItemLotFacts :many
WITH lot_facts AS (
    SELECT
        lot.id,
        lot.item_id,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.originated_on,
        lot.expires_on,
        lot.created_at_ms,
        source_document.id AS source_document_id,
        source_document.kind AS source_document_kind,
        source_document.posting_sequence AS source_posting_sequence,
        source_document.occurred_on AS source_occurred_on,
        CAST(COALESCE(SUM(
            CASE WHEN allocation.restores_allocation_id IS NULL
                THEN allocation.quantity_atomic ELSE 0 END
        ), 0) AS INTEGER) AS consumed_quantity_atomic,
        CAST(COALESCE(SUM(
            CASE WHEN allocation.restores_allocation_id IS NOT NULL
                THEN allocation.quantity_atomic ELSE 0 END
        ), 0) AS INTEGER) AS restored_quantity_atomic,
        lot.initial_quantity_atomic
            - COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0)
            + COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NOT NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0) AS remaining_quantity_atomic
    FROM inventory_lots lot
    JOIN stock_document_lines source_line ON source_line.id = lot.source_line_id
    JOIN stock_documents source_document ON source_document.id = source_line.document_id
    LEFT JOIN lot_allocations allocation ON allocation.lot_id = lot.id
    WHERE lot.item_id = ?1
    GROUP BY
        lot.id,
        lot.item_id,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.originated_on,
        lot.expires_on,
        lot.created_at_ms,
        source_document.id,
        source_document.kind,
        source_document.posting_sequence,
        source_document.occurred_on
)
SELECT
    id,
    item_id,
    source_line_id,
    initial_quantity_atomic,
    consumed_quantity_atomic,
    restored_quantity_atomic,
    remaining_quantity_atomic,
    lot_code,
    originated_on,
    expires_on,
    created_at_ms,
    source_document_id,
    source_document_kind,
    source_posting_sequence,
    source_occurred_on
FROM lot_facts
ORDER BY
    expires_on IS NULL,
    expires_on,
    source_posting_sequence,
    id
`

type ListItemLotFactsRow struct {
	ID                      int64
	ItemID                  int64
	SourceLineID            int64
	InitialQuantityAtomic   int64
	ConsumedQuantityAtomic  int64
	RestoredQuantityAtomic  int64
	RemainingQuantityAtomic int64
	LotCode                 sql.NullString
	OriginatedOn            string
	ExpiresOn               sql.NullString
	CreatedAtMs             int64
	SourceDocumentID        int64
	SourceDocumentKind      string
	SourcePostingSequence   int64
	SourceOccurredOn        string
}

func (q *Queries) ListItemLotFacts(ctx context.Context, itemID int64) ([]ListItemLotFactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemLotFacts, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemLotFactsRow{}
	for rows.Next() {
		var i ListItemLotFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SourceLineID,
			&i.InitialQuantityAtomic,
			&i.ConsumedQuantityAtomic,
			&i.RestoredQuantityAtomic,
			&i.RemainingQuantityAtomic,
			&i.LotCode,
			&i.OriginatedOn,
			&i.ExpiresOn,
			&i.CreatedAtMs,
			&i.SourceDocumentID,
			&i.SourceDocumentKind,
			&i.SourcePostingSequence,
			&i.SourceOccurredOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineAllocations = `-- name: ListLineAllocations :many
SELECT
    allocation.id,
    allocation.line_id,
    allocation.lot_id,
    allocation.quantity_atomic,
    allocation.restores_allocation_id,
    allocation.created_at_ms,
    lot.source_line_id,
    lot.initial_quantity_atomic AS lot_initial_quantity_atomic,
    lot.lot_code,
    lot.originated_on,
    lot.expires_on
FROM lot_allocations allocation
JOIN inventory_lots lot ON lot.id = allocation.lot_id
WHERE allocation.line_id = ?1
ORDER BY allocation.id
`

type ListLineAllocationsRow struct {
	ID                       int64
	LineID                   int64
	LotID                    int64
	QuantityAtomic           int64
	RestoresAllocationID     sql.NullInt64
	CreatedAtMs              int64
	SourceLineID             int64
	LotInitialQuantityAtomic int64
	LotCode                  sql.NullString
	OriginatedOn             string
	ExpiresOn                sql.NullString
}

func (q *Queries) ListLineAllocations(ctx context.Context, lineID int64) ([]ListLineAllocationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLineAllocations, lineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLineAllocationsRow{}
	for rows.Next() {
		var i ListLineAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.LineID,
			&i.LotID,
			&i.QuantityAtomic,
			&i.RestoresAllocationID,
			&i.CreatedAtMs,
			&i.SourceLineID,
			&i.LotInitialQuantityAtomic,
			&i.LotCode,
			&i.OriginatedOn,
			&i.ExpiresOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
