// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type AppSetting struct {
	ID                            int64
	BusinessName                  string
	LocaleCode                    string
	TimezoneName                  string
	CurrencyCode                  string
	CurrencyMinorDigits           int64
	HourlyLaborCostMinor          sql.NullInt64
	DefaultGrossMarginBasisPoints sql.NullInt64
	CreatedAtMs                   int64
	UpdatedAtMs                   int64
}

type CounterpartyRole struct {
	CounterpartyID int64
	Role           string
	CreatedAtMs    int64
}

type Item struct {
	ID                    int64
	Name                  string
	NormalizedName        string
	SKU                   sql.NullString
	NormalizedSKU         sql.NullString
	Description           sql.NullString
	BaseUnitCode          string
	IsPurchasable         int64
	IsProducible          int64
	IsSellable            int64
	DefaultSalePriceMinor sql.NullInt64
	ReorderQuantityAtomic sql.NullInt64
	CreatedAtMs           int64
	UpdatedAtMs           int64
	ArchivedAtMs          sql.NullInt64
}

type ItemPackaging struct {
	ID                        int64
	ItemID                    int64
	Name                      string
	NormalizedName            string
	EnteredUnitCode           string
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	CreatedAtMs               int64
	UpdatedAtMs               int64
	ArchivedAtMs              sql.NullInt64
}

type MeasurementUnit struct {
	Code              string
	Name              string
	Symbol            string
	Dimension         string
	AtomicNumerator   int64
	AtomicDenominator int64
	IsItemBase        int64
	IsSeeded          int64
}

type Recipe struct {
	ID             int64
	Name           string
	NormalizedName string
	OutputItemID   int64
	CreatedAtMs    int64
	UpdatedAtMs    int64
	ArchivedAtMs   sql.NullInt64
}

type RecipeRevision struct {
	ID                          int64
	RecipeID                    int64
	RevisionNumber              int64
	StandardYieldQuantityAtomic int64
	Instructions                string
	PreparationTimeMinutes      int64
	EstimatedDirectCostMicro    sql.NullInt64
	CreatedAtMs                 int64
}

type RecipeRevisionComponent struct {
	ID                        int64
	RecipeRevisionID          int64
	ComponentOrder            int64
	ItemID                    int64
	QuantityAtomic            int64
	EnteredUnitCode           string
	EnteredPackagingName      sql.NullString
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	CreatedAtMs               int64
}
