// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	AdvanceRecipeVersion(ctx context.Context, arg AdvanceRecipeVersionParams) (int64, error)
	ArchiveCounterparty(ctx context.Context, arg ArchiveCounterpartyParams) (int64, error)
	ArchiveItem(ctx context.Context, arg ArchiveItemParams) (int64, error)
	ArchiveItemPackaging(ctx context.Context, arg ArchiveItemPackagingParams) (int64, error)
	ArchiveRecipe(ctx context.Context, arg ArchiveRecipeParams) (int64, error)
	DeleteCounterpartyRoles(ctx context.Context, counterpartyID int64) (int64, error)
	GetAppSettings(ctx context.Context) (AppSetting, error)
	GetCounterparty(ctx context.Context, id int64) (GetCounterpartyRow, error)
	GetCurrentRecipe(ctx context.Context, targetRecipeID int64) (GetCurrentRecipeRow, error)
	GetInventoryBalance(ctx context.Context, itemID int64) (GetInventoryBalanceRow, error)
	GetItem(ctx context.Context, id int64) (Item, error)
	GetItemPackaging(ctx context.Context, id int64) (ItemPackaging, error)
	GetLatestRecipeRevisionNumber(ctx context.Context, recipeID int64) (int64, error)
	GetMeasurementUnit(ctx context.Context, code string) (MeasurementUnit, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	GetRecipeRevision(ctx context.Context, id int64) (GetRecipeRevisionRow, error)
	InsertCounterparty(ctx context.Context, arg InsertCounterpartyParams) (int64, error)
	InsertCounterpartyRole(ctx context.Context, arg InsertCounterpartyRoleParams) error
	InsertItem(ctx context.Context, arg InsertItemParams) (int64, error)
	InsertItemPackaging(ctx context.Context, arg InsertItemPackagingParams) (int64, error)
	InsertRecipe(ctx context.Context, arg InsertRecipeParams) (int64, error)
	InsertRecipeRevision(ctx context.Context, arg InsertRecipeRevisionParams) (int64, error)
	InsertRecipeRevisionComponent(ctx context.Context, arg InsertRecipeRevisionComponentParams) (int64, error)
	ListCounterparties(ctx context.Context, arg ListCounterpartiesParams) ([]ListCounterpartiesRow, error)
	ListCounterpartyRoles(ctx context.Context, counterpartyID int64) ([]CounterpartyRole, error)
	ListEligibleFEFOLots(ctx context.Context, arg ListEligibleFEFOLotsParams) ([]ListEligibleFEFOLotsRow, error)
	ListInventoryBalances(ctx context.Context, arg ListInventoryBalancesParams) ([]ListInventoryBalancesRow, error)
	ListItemLedgerPage(ctx context.Context, arg ListItemLedgerPageParams) ([]ListItemLedgerPageRow, error)
	ListItemLotFacts(ctx context.Context, itemID int64) ([]ListItemLotFactsRow, error)
	ListItemPackagings(ctx context.Context, arg ListItemPackagingsParams) ([]ItemPackaging, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
	ListLineAllocations(ctx context.Context, lineID int64) ([]ListLineAllocationsRow, error)
	ListMeasurementUnits(ctx context.Context) ([]MeasurementUnit, error)
	ListRecipeRevisionComponents(ctx context.Context, recipeRevisionID int64) ([]RecipeRevisionComponent, error)
	ListRecipeRevisions(ctx context.Context, recipeID int64) ([]RecipeRevision, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error)
	ReconfigureArchivedItemPackaging(ctx context.Context, arg ReconfigureArchivedItemPackagingParams) (int64, error)
	RenameRecipe(ctx context.Context, arg RenameRecipeParams) (int64, error)
	RestoreCounterparty(ctx context.Context, arg RestoreCounterpartyParams) (int64, error)
	RestoreItem(ctx context.Context, arg RestoreItemParams) (int64, error)
	RestoreItemPackaging(ctx context.Context, arg RestoreItemPackagingParams) (int64, error)
	RestoreRecipe(ctx context.Context, arg RestoreRecipeParams) (int64, error)
	UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) (AppSetting, error)
	UpdateCounterparty(ctx context.Context, arg UpdateCounterpartyParams) (int64, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error)
	UpdateItemPackaging(ctx context.Context, arg UpdateItemPackagingParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
