// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const advanceRecipeVersion = `-- name: AdvanceRecipeVersion :execrows
UPDATE recipes
SET updated_at_ms = ?1
WHERE id = ?2
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?3
`

type AdvanceRecipeVersionParams struct {
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) AdvanceRecipeVersion(ctx context.Context, arg AdvanceRecipeVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceRecipeVersion, arg.UpdatedAtMs, arg.ID, arg.ExpectedUpdatedAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const archiveRecipe = `-- name: ArchiveRecipe :execrows
UPDATE recipes
SET
    archived_at_ms = CAST(?1 AS INTEGER),
    updated_at_ms = ?2
WHERE id = ?3
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?4
`

type ArchiveRecipeParams struct {
	ArchivedAtMs        int64
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) ArchiveRecipe(ctx context.Context, arg ArchiveRecipeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveRecipe,
		arg.ArchivedAtMs,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCurrentRecipe = `-- name: GetCurrentRecipe :one
SELECT
    recipe.id AS recipe_id,
    recipe.name AS recipe_name,
    recipe.normalized_name AS recipe_normalized_name,
    recipe.output_item_id,
    recipe.created_at_ms AS recipe_created_at_ms,
    recipe.updated_at_ms AS recipe_updated_at_ms,
    recipe.archived_at_ms AS recipe_archived_at_ms,
    revision.id AS revision_id,
    revision.revision_number,
    revision.standard_yield_quantity_atomic,
    revision.instructions,
    revision.preparation_time_minutes,
    revision.estimated_direct_cost_micro,
    revision.created_at_ms AS revision_created_at_ms,
    CAST(COALESCE(revision_chain.revision_count, 0) AS INTEGER) AS revision_count,
    CAST(COALESCE(revision_chain.minimum_revision_number, 0) AS INTEGER) AS minimum_revision_number
FROM recipes recipe
JOIN (
    SELECT
        historical.recipe_id,
        CAST(COUNT(*) AS INTEGER) AS revision_count,
        CAST(MIN(historical.revision_number) AS INTEGER) AS minimum_revision_number,
        CAST(MAX(historical.revision_number) AS INTEGER) AS latest_revision_number
    FROM recipe_revisions historical
    WHERE historical.recipe_id = ?1
    GROUP BY historical.recipe_id
) revision_chain ON revision_chain.recipe_id = recipe.id
JOIN recipe_revisions revision
  ON revision.recipe_id = revision_chain.recipe_id
 AND revision.revision_number = revision_chain.latest_revision_number
WHERE recipe.id = ?1
`

type GetCurrentRecipeRow struct {
	RecipeID                    int64
	RecipeName                  string
	RecipeNormalizedName        string
	OutputItemID                int64
	RecipeCreatedAtMs           int64
	RecipeUpdatedAtMs           int64
	RecipeArchivedAtMs          sql.NullInt64
	RevisionID                  int64
	RevisionNumber              int64
	StandardYieldQuantityAtomic int64
	Instructions                string
	PreparationTimeMinutes      int64
	EstimatedDirectCostMicro    sql.NullInt64
	RevisionCreatedAtMs         int64
	RevisionCount               int64
	MinimumRevisionNumber       int64
}

func (q *Queries) GetCurrentRecipe(ctx context.Context, targetRecipeID int64) (GetCurrentRecipeRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentRecipe, targetRecipeID)
	var i GetCurrentRecipeRow
	err := row.Scan(
		&i.RecipeID,
		&i.RecipeName,
		&i.RecipeNormalizedName,
		&i.OutputItemID,
		&i.RecipeCreatedAtMs,
		&i.RecipeUpdatedAtMs,
		&i.RecipeArchivedAtMs,
		&i.RevisionID,
		&i.RevisionNumber,
		&i.StandardYieldQuantityAtomic,
		&i.Instructions,
		&i.PreparationTimeMinutes,
		&i.EstimatedDirectCostMicro,
		&i.RevisionCreatedAtMs,
		&i.RevisionCount,
		&i.MinimumRevisionNumber,
	)
	return i, err
}

const getLatestRecipeRevisionNumber = `-- name: GetLatestRecipeRevisionNumber :one
SELECT CAST(COALESCE(MAX(revision_number), 0) AS INTEGER) AS latest_revision_number
FROM recipe_revisions
WHERE recipe_id = ?1
`

func (q *Queries) GetLatestRecipeRevisionNumber(ctx context.Context, recipeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLatestRecipeRevisionNumber, recipeID)
	var latest_revision_number int64
	err := row.Scan(&latest_revision_number)
	return latest_revision_number, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT
    id,
    name,
    normalized_name,
    output_item_id,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
FROM recipes
WHERE id = ?1
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NormalizedName,
		&i.OutputItemID,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
		&i.ArchivedAtMs,
	)
	return i, err
}

const getRecipeRevision = `-- name: GetRecipeRevision :one
SELECT
    id,
    recipe_id,
    revision_number,
    standard_yield_quantity_atomic,
    instructions,
    preparation_time_minutes,
    estimated_direct_cost_micro,
    created_at_ms,
    CAST((
        SELECT COUNT(*)
        FROM recipe_revisions historical
        WHERE historical.recipe_id = revision.recipe_id
    ) AS INTEGER) AS revision_count,
    CAST((
        SELECT MIN(historical.revision_number)
        FROM recipe_revisions historical
        WHERE historical.recipe_id = revision.recipe_id
    ) AS INTEGER) AS minimum_revision_number,
    CAST((
        SELECT MAX(historical.revision_number)
        FROM recipe_revisions historical
        WHERE historical.recipe_id = revision.recipe_id
    ) AS INTEGER) AS latest_revision_number
FROM recipe_revisions revision
WHERE revision.id = ?1
`

type GetRecipeRevisionRow struct {
	ID                          int64
	RecipeID                    int64
	RevisionNumber              int64
	StandardYieldQuantityAtomic int64
	Instructions                string
	PreparationTimeMinutes      int64
	EstimatedDirectCostMicro    sql.NullInt64
	CreatedAtMs                 int64
	RevisionCount               int64
	MinimumRevisionNumber       int64
	LatestRevisionNumber        int64
}

func (q *Queries) GetRecipeRevision(ctx context.Context, id int64) (GetRecipeRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, getRecipeRevision, id)
	var i GetRecipeRevisionRow
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.RevisionNumber,
		&i.StandardYieldQuantityAtomic,
		&i.Instructions,
		&i.PreparationTimeMinutes,
		&i.EstimatedDirectCostMicro,
		&i.CreatedAtMs,
		&i.RevisionCount,
		&i.MinimumRevisionNumber,
		&i.LatestRevisionNumber,
	)
	return i, err
}

const insertRecipe = `-- name: InsertRecipe :one
INSERT INTO recipes (
    name,
    normalized_name,
    output_item_id,
    created_at_ms,
    updated_at_ms,
    archived_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    NULL
)
RETURNING id
`

type InsertRecipeParams struct {
	Name           string
	NormalizedName string
	OutputItemID   int64
	CreatedAtMs    int64
	UpdatedAtMs    int64
}

func (q *Queries) InsertRecipe(ctx context.Context, arg InsertRecipeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecipe,
		arg.Name,
		arg.NormalizedName,
		arg.OutputItemID,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRecipeRevision = `-- name: InsertRecipeRevision :one
INSERT INTO recipe_revisions (
    recipe_id,
    revision_number,
    standard_yield_quantity_atomic,
    instructions,
    preparation_time_minutes,
    estimated_direct_cost_micro,
    created_at_ms
) SELECT
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
WHERE CAST(?8 AS INTEGER) = (
    SELECT CAST(COALESCE(MAX(existing.revision_number), 0) AS INTEGER)
    FROM recipe_revisions existing
    WHERE existing.recipe_id = ?1
)
  AND ?2 = CAST(?8 AS INTEGER) + 1
RETURNING id
`

type InsertRecipeRevisionParams struct {
	RecipeID                     int64
	RevisionNumber               int64
	StandardYieldQuantityAtomic  int64
	Instructions                 string
	PreparationTimeMinutes       int64
	EstimatedDirectCostMicro     sql.NullInt64
	CreatedAtMs                  int64
	ExpectedLatestRevisionNumber int64
}

func (q *Queries) InsertRecipeRevision(ctx context.Context, arg InsertRecipeRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecipeRevision,
		arg.RecipeID,
		arg.RevisionNumber,
		arg.StandardYieldQuantityAtomic,
		arg.Instructions,
		arg.PreparationTimeMinutes,
		arg.EstimatedDirectCostMicro,
		arg.CreatedAtMs,
		arg.ExpectedLatestRevisionNumber,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRecipeRevisionComponent = `-- name: InsertRecipeRevisionComponent :one
INSERT INTO recipe_revision_components (
    recipe_revision_id,
    component_order,
    item_id,
    quantity_atomic,
    entered_unit_code,
    entered_packaging_name,
    conversion_numerator_atomic,
    conversion_denominator,
    created_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
RETURNING id
`

type InsertRecipeRevisionComponentParams struct {
	RecipeRevisionID          int64
	ComponentOrder            int64
	ItemID                    int64
	QuantityAtomic            int64
	EnteredUnitCode           string
	EnteredPackagingName      sql.NullString
	ConversionNumeratorAtomic int64
	ConversionDenominator     int64
	CreatedAtMs               int64
}

func (q *Queries) InsertRecipeRevisionComponent(ctx context.Context, arg InsertRecipeRevisionComponentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRecipeRevisionComponent,
		arg.RecipeRevisionID,
		arg.ComponentOrder,
		arg.ItemID,
		arg.QuantityAtomic,
		arg.EnteredUnitCode,
		arg.EnteredPackagingName,
		arg.ConversionNumeratorAtomic,
		arg.ConversionDenominator,
		arg.CreatedAtMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listRecipeRevisionComponents = `-- name: ListRecipeRevisionComponents :many
SELECT
    id,
    recipe_revision_id,
    component_order,
    item_id,
    quantity_atomic,
    entered_unit_code,
    entered_packaging_name,
    conversion_numerator_atomic,
    conversion_denominator,
    created_at_ms
FROM recipe_revision_components
WHERE recipe_revision_id = ?1
ORDER BY component_order, id
`

func (q *Queries) ListRecipeRevisionComponents(ctx context.Context, recipeRevisionID int64) ([]RecipeRevisionComponent, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeRevisionComponents, recipeRevisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRevisionComponent{}
	for rows.Next() {
		var i RecipeRevisionComponent
		if err := rows.Scan(
			&i.ID,
			&i.RecipeRevisionID,
			&i.ComponentOrder,
			&i.ItemID,
			&i.QuantityAtomic,
			&i.EnteredUnitCode,
			&i.EnteredPackagingName,
			&i.ConversionNumeratorAtomic,
			&i.ConversionDenominator,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeRevisions = `-- name: ListRecipeRevisions :many
SELECT
    id,
    recipe_id,
    revision_number,
    standard_yield_quantity_atomic,
    instructions,
    preparation_time_minutes,
    estimated_direct_cost_micro,
    created_at_ms
FROM recipe_revisions
WHERE recipe_id = ?1
ORDER BY revision_number DESC
`

func (q *Queries) ListRecipeRevisions(ctx context.Context, recipeID int64) ([]RecipeRevision, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeRevisions, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeRevision{}
	for rows.Next() {
		var i RecipeRevision
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.RevisionNumber,
			&i.StandardYieldQuantityAtomic,
			&i.Instructions,
			&i.PreparationTimeMinutes,
			&i.EstimatedDirectCostMicro,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT
    recipe.id,
    recipe.name,
    recipe.normalized_name,
    recipe.output_item_id,
    output.name AS output_item_name,
    recipe.created_at_ms,
    recipe.updated_at_ms,
    recipe.archived_at_ms,
    current_revision.id AS current_revision_id,
    current_revision.revision_number AS current_revision_number,
    current_revision.standard_yield_quantity_atomic AS current_standard_yield_quantity_atomic,
    CAST(COALESCE(revision_chain.revision_count, 0) AS INTEGER) AS revision_count,
    CAST(COALESCE(revision_chain.minimum_revision_number, 0) AS INTEGER) AS minimum_revision_number
FROM recipes recipe
JOIN items output ON output.id = recipe.output_item_id
LEFT JOIN (
    SELECT
        historical.recipe_id,
        CAST(COUNT(*) AS INTEGER) AS revision_count,
        CAST(MIN(historical.revision_number) AS INTEGER) AS minimum_revision_number,
        CAST(MAX(historical.revision_number) AS INTEGER) AS latest_revision_number
    FROM recipe_revisions historical
    GROUP BY historical.recipe_id
) revision_chain ON revision_chain.recipe_id = recipe.id
LEFT JOIN recipe_revisions current_revision
  ON current_revision.recipe_id = revision_chain.recipe_id
 AND current_revision.revision_number = revision_chain.latest_revision_number
WHERE
    (
        CAST(?1 AS INTEGER) = 2
        OR (CAST(?1 AS INTEGER) = 0 AND recipe.archived_at_ms IS NULL)
        OR (CAST(?1 AS INTEGER) = 1 AND recipe.archived_at_ms IS NOT NULL)
    )
    AND (
        CAST(?2 AS TEXT) = ''
        OR instr(recipe.normalized_name, CAST(?2 AS TEXT)) > 0
    )
    AND (
        CAST(?3 AS TEXT) = ''
        OR recipe.normalized_name > CAST(?3 AS TEXT)
        OR (
            recipe.normalized_name = CAST(?3 AS TEXT)
            AND recipe.id > ?4
        )
    )
ORDER BY recipe.normalized_name, recipe.id
LIMIT ?5
`

type ListRecipesParams struct {
	ArchiveFilter       int64
	SearchKey           string
	AfterNormalizedName string
	AfterID             int64
	LimitCount          int64
}

type ListRecipesRow struct {
	ID                                 int64
	Name                               string
	NormalizedName                     string
	OutputItemID                       int64
	OutputItemName                     string
	CreatedAtMs                        int64
	UpdatedAtMs                        int64
	ArchivedAtMs                       sql.NullInt64
	CurrentRevisionID                  sql.NullInt64
	CurrentRevisionNumber              sql.NullInt64
	CurrentStandardYieldQuantityAtomic sql.NullInt64
	RevisionCount                      int64
	MinimumRevisionNumber              int64
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]ListRecipesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes,
		arg.ArchiveFilter,
		arg.SearchKey,
		arg.AfterNormalizedName,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecipesRow{}
	for rows.Next() {
		var i ListRecipesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NormalizedName,
			&i.OutputItemID,
			&i.OutputItemName,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
			&i.ArchivedAtMs,
			&i.CurrentRevisionID,
			&i.CurrentRevisionNumber,
			&i.CurrentStandardYieldQuantityAtomic,
			&i.RevisionCount,
			&i.MinimumRevisionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameRecipe = `-- name: RenameRecipe :execrows
UPDATE recipes
SET
    name = ?1,
    normalized_name = ?2,
    updated_at_ms = ?3
WHERE id = ?4
  AND archived_at_ms IS NULL
  AND updated_at_ms = ?5
`

type RenameRecipeParams struct {
	Name                string
	NormalizedName      string
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) RenameRecipe(ctx context.Context, arg RenameRecipeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameRecipe,
		arg.Name,
		arg.NormalizedName,
		arg.UpdatedAtMs,
		arg.ID,
		arg.ExpectedUpdatedAtMs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreRecipe = `-- name: RestoreRecipe :execrows
UPDATE recipes
SET
    archived_at_ms = NULL,
    updated_at_ms = ?1
WHERE id = ?2
  AND archived_at_ms IS NOT NULL
  AND updated_at_ms = ?3
`

type RestoreRecipeParams struct {
	UpdatedAtMs         int64
	ID                  int64
	ExpectedUpdatedAtMs int64
}

func (q *Queries) RestoreRecipe(ctx context.Context, arg RestoreRecipeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreRecipe, arg.UpdatedAtMs, arg.ID, arg.ExpectedUpdatedAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
