// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getAnonymousSalesTotals = `-- name: GetAnonymousSalesTotals :one
WITH anonymous_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.commercial_total_minor
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.counterparty_id IS NULL
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor
FROM anonymous_sale_lines
`

type GetAnonymousSalesTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetAnonymousSalesTotalsRow struct {
	DocumentCount int64
	RevenueMinor  int64
}

func (q *Queries) GetAnonymousSalesTotals(ctx context.Context, arg GetAnonymousSalesTotalsParams) (GetAnonymousSalesTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getAnonymousSalesTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetAnonymousSalesTotalsRow
	err := row.Scan(&i.DocumentCount, &i.RevenueMinor)
	return i, err
}

const getFreeSalesTotals = `-- name: GetFreeSalesTotals :one
WITH free_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.reason_code IN ('PROMOTION', 'SAMPLE')
      AND line.commercial_total_minor = 0
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM free_sale_lines
`

type GetFreeSalesTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetFreeSalesTotalsRow struct {
	DocumentCount  int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) GetFreeSalesTotals(ctx context.Context, arg GetFreeSalesTotalsParams) (GetFreeSalesTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getFreeSalesTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetFreeSalesTotalsRow
	err := row.Scan(
		&i.DocumentCount,
		&i.QuantityAtomic,
		&i.RevenueMinor,
		&i.CogsMicro,
	)
	return i, err
}

const getInventoryReportTotals = `-- name: GetInventoryReportTotals :one
SELECT
    CAST(COALESCE(SUM(balance.inventory_value_micro), 0) AS INTEGER) AS total_inventory_value_micro,
    CAST(COALESCE(SUM(
        CASE
            WHEN item.archived_at_ms IS NULL
             AND item.reorder_quantity_atomic IS NOT NULL
             AND balance.quantity_atomic <= item.reorder_quantity_atomic
                THEN 1 ELSE 0
        END
    ), 0) AS INTEGER) AS low_stock_item_count,
    CAST(COALESCE(SUM(
        CASE
            WHEN item.archived_at_ms IS NULL
             AND item.is_sellable = 1
             AND balance.quantity_atomic = 0
                THEN 1 ELSE 0
        END
    ), 0) AS INTEGER) AS zero_stock_sellable_count
FROM inventory_balances balance
JOIN items item ON item.id = balance.item_id
`

type GetInventoryReportTotalsRow struct {
	TotalInventoryValueMicro int64
	LowStockItemCount        int64
	ZeroStockSellableCount   int64
}

func (q *Queries) GetInventoryReportTotals(ctx context.Context) (GetInventoryReportTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getInventoryReportTotals)
	var i GetInventoryReportTotalsRow
	err := row.Scan(&i.TotalInventoryValueMicro, &i.LowStockItemCount, &i.ZeroStockSellableCount)
	return i, err
}

const getReportingCurrency = `-- name: GetReportingCurrency :one
SELECT currency_code, currency_minor_digits
FROM app_settings
WHERE id = 1
`

type GetReportingCurrencyRow struct {
	CurrencyCode        string
	CurrencyMinorDigits int64
}

func (q *Queries) GetReportingCurrency(ctx context.Context) (GetReportingCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getReportingCurrency)
	var i GetReportingCurrencyRow
	err := row.Scan(&i.CurrencyCode, &i.CurrencyMinorDigits)
	return i, err
}

const getSalesReportTotals = `-- name: GetSalesReportTotals :one
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS sales_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
`

type GetSalesReportTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetSalesReportTotalsRow struct {
	SalesCount     int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) GetSalesReportTotals(ctx context.Context, arg GetSalesReportTotalsParams) (GetSalesReportTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesReportTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetSalesReportTotalsRow
	err := row.Scan(
		&i.SalesCount,
		&i.QuantityAtomic,
		&i.RevenueMinor,
		&i.CogsMicro,
	)
	return i, err
}

const listAdjustmentReasonMetrics = `-- name: ListAdjustmentReasonMetrics :many
WITH active_adjustment_lines AS (
    SELECT
        document.id AS document_id,
        document.reason_code,
        line.direction,
        line.quantity_atomic,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'ADJUSTMENT'
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND line.direction = CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(reason_code AS TEXT) AS reason_code,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro
FROM active_adjustment_lines
GROUP BY reason_code
ORDER BY inventory_value_micro DESC, quantity_atomic DESC, reason_code
`

type ListAdjustmentReasonMetricsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
	Direction      string
}

type ListAdjustmentReasonMetricsRow struct {
	ReasonCode          string
	DocumentCount       int64
	QuantityAtomic      int64
	InventoryValueMicro int64
}

func (q *Queries) ListAdjustmentReasonMetrics(ctx context.Context, arg ListAdjustmentReasonMetricsParams) ([]ListAdjustmentReasonMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdjustmentReasonMetrics, arg.FromOccurredOn, arg.ToOccurredOn, arg.Direction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdjustmentReasonMetricsRow{}
	for rows.Next() {
		var i ListAdjustmentReasonMetricsRow
		if err := rows.Scan(
			&i.ReasonCode,
			&i.DocumentCount,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExactReversalSeries = `-- name: ListExactReversalSeries :many
WITH exact_reversal_lines AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        line.quantity_atomic,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'REVERSAL'
      AND document.reason_code = 'EXACT_REVERSAL'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro
FROM exact_reversal_lines
GROUP BY bucket
ORDER BY bucket
`

type ListExactReversalSeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListExactReversalSeriesRow struct {
	Bucket              string
	Label               string
	DocumentCount       int64
	QuantityAtomic      int64
	InventoryValueMicro int64
}

func (q *Queries) ListExactReversalSeries(ctx context.Context, arg ListExactReversalSeriesParams) ([]ListExactReversalSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExactReversalSeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExactReversalSeriesRow{}
	for rows.Next() {
		var i ListExactReversalSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.DocumentCount,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredLotsWithStock = `-- name: ListExpiredLotsWithStock :many
WITH lot_facts AS (
    SELECT
        lot.id,
        lot.item_id,
        item.name AS item_name,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.expires_on,
        source_line.inventory_value_micro AS source_inventory_value_micro,
        source_line.quantity_atomic AS source_quantity_atomic,
        lot.initial_quantity_atomic
            - COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0)
            + COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NOT NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0) AS available_quantity_atomic
    FROM inventory_lots lot
    JOIN items item ON item.id = lot.item_id
    JOIN stock_document_lines source_line ON source_line.id = lot.source_line_id
    LEFT JOIN lot_allocations allocation ON allocation.lot_id = lot.id
    WHERE item.archived_at_ms IS NULL
      AND lot.expires_on IS NOT NULL
    GROUP BY lot.id
)
SELECT
    id AS lot_id,
    item_id,
    item_name,
    lot_code,
    expires_on,
    CAST(available_quantity_atomic AS INTEGER) AS available_quantity_atomic,
    CAST(
        (source_inventory_value_micro * available_quantity_atomic) / source_quantity_atomic
        AS INTEGER
    ) AS inventory_value_micro
FROM lot_facts
WHERE available_quantity_atomic > 0
  AND expires_on <= CAST(?1 AS TEXT)
ORDER BY expires_on, item_name, id
LIMIT ?2
`

type ListExpiredLotsWithStockParams struct {
	ReferenceDate string
	LimitCount    int64
}

type ListExpiredLotsWithStockRow struct {
	LotID                   int64
	ItemID                  int64
	ItemName                string
	LotCode                 sql.NullString
	ExpiresOn               sql.NullString
	AvailableQuantityAtomic int64
	InventoryValueMicro     int64
}

func (q *Queries) ListExpiredLotsWithStock(ctx context.Context, arg ListExpiredLotsWithStockParams) ([]ListExpiredLotsWithStockRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredLotsWithStock, arg.ReferenceDate, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredLotsWithStockRow{}
	for rows.Next() {
		var i ListExpiredLotsWithStockRow
		if err := rows.Scan(
			&i.LotID,
			&i.ItemID,
			&i.ItemName,
			&i.LotCode,
			&i.ExpiresOn,
			&i.AvailableQuantityAtomic,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringLots = `-- name: ListExpiringLots :many
WITH lot_facts AS (
    SELECT
        lot.id,
        lot.item_id,
        item.name AS item_name,
        lot.source_line_id,
        lot.initial_quantity_atomic,
        lot.lot_code,
        lot.expires_on,
        source_line.inventory_value_micro AS source_inventory_value_micro,
        source_line.quantity_atomic AS source_quantity_atomic,
        lot.initial_quantity_atomic
            - COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0)
            + COALESCE(SUM(
                CASE WHEN allocation.restores_allocation_id IS NOT NULL
                    THEN allocation.quantity_atomic ELSE 0 END
            ), 0) AS available_quantity_atomic
    FROM inventory_lots lot
    JOIN items item ON item.id = lot.item_id
    JOIN stock_document_lines source_line ON source_line.id = lot.source_line_id
    LEFT JOIN lot_allocations allocation ON allocation.lot_id = lot.id
    WHERE item.archived_at_ms IS NULL
      AND lot.expires_on IS NOT NULL
    GROUP BY lot.id
)
SELECT
    id AS lot_id,
    item_id,
    item_name,
    lot_code,
    expires_on,
    CAST(available_quantity_atomic AS INTEGER) AS available_quantity_atomic,
    CAST(
        (source_inventory_value_micro * available_quantity_atomic) / source_quantity_atomic
        AS INTEGER
    ) AS inventory_value_micro
FROM lot_facts
WHERE available_quantity_atomic > 0
  AND expires_on > CAST(?1 AS TEXT)
  AND expires_on <= date(
      CAST(?1 AS TEXT),
      '+' || CAST(?2 AS INTEGER) || ' day'
  )
ORDER BY expires_on, item_name, id
LIMIT ?3
`

type ListExpiringLotsParams struct {
	ReferenceDate string
	DaysAhead     int64
	LimitCount    int64
}

type ListExpiringLotsRow struct {
	LotID                   int64
	ItemID                  int64
	ItemName                string
	LotCode                 sql.NullString
	ExpiresOn               sql.NullString
	AvailableQuantityAtomic int64
	InventoryValueMicro     int64
}

func (q *Queries) ListExpiringLots(ctx context.Context, arg ListExpiringLotsParams) ([]ListExpiringLotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringLots, arg.ReferenceDate, arg.DaysAhead, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringLotsRow{}
	for rows.Next() {
		var i ListExpiringLotsRow
		if err := rows.Scan(
			&i.LotID,
			&i.ItemID,
			&i.ItemName,
			&i.LotCode,
			&i.ExpiresOn,
			&i.AvailableQuantityAtomic,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeStockEntrySeries = `-- name: ListFreeStockEntrySeries :many
WITH free_stock_lines AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'PURCHASE'
      AND document.reason_code = 'FREE_STOCK'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS spend_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro
FROM free_stock_lines
GROUP BY bucket
ORDER BY bucket
`

type ListFreeStockEntrySeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListFreeStockEntrySeriesRow struct {
	Bucket              string
	Label               string
	DocumentCount       int64
	QuantityAtomic      int64
	SpendMinor          int64
	InventoryValueMicro int64
}

func (q *Queries) ListFreeStockEntrySeries(ctx context.Context, arg ListFreeStockEntrySeriesParams) ([]ListFreeStockEntrySeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFreeStockEntrySeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFreeStockEntrySeriesRow{}
	for rows.Next() {
		var i ListFreeStockEntrySeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.DocumentCount,
			&i.QuantityAtomic,
			&i.SpendMinor,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryValueByItem = `-- name: ListInventoryValueByItem :many
SELECT
    item.id AS item_id,
    item.name AS item_name,
    item.base_unit_code,
    balance.quantity_atomic,
    balance.inventory_value_micro
FROM inventory_balances balance
JOIN items item ON item.id = balance.item_id
WHERE item.archived_at_ms IS NULL
  AND balance.inventory_value_micro > 0
ORDER BY balance.inventory_value_micro DESC, item.name, item.id
LIMIT ?1
`

type ListInventoryValueByItemRow struct {
	ItemID              int64
	ItemName            string
	BaseUnitCode        string
	QuantityAtomic      int64
	InventoryValueMicro int64
}

func (q *Queries) ListInventoryValueByItem(ctx context.Context, limitCount int64) ([]ListInventoryValueByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryValueByItem, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryValueByItemRow{}
	for rows.Next() {
		var i ListInventoryValueByItemRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockItems = `-- name: ListLowStockItems :many
SELECT
    item.id AS item_id,
    item.name AS item_name,
    item.base_unit_code,
    balance.quantity_atomic,
    balance.inventory_value_micro,
    item.reorder_quantity_atomic
FROM inventory_balances balance
JOIN items item ON item.id = balance.item_id
WHERE item.archived_at_ms IS NULL
  AND item.reorder_quantity_atomic IS NOT NULL
  AND balance.quantity_atomic <= item.reorder_quantity_atomic
ORDER BY (item.reorder_quantity_atomic - balance.quantity_atomic) DESC, item.name, item.id
LIMIT ?1
`

type ListLowStockItemsRow struct {
	ItemID                int64
	ItemName              string
	BaseUnitCode          string
	QuantityAtomic        int64
	InventoryValueMicro   int64
	ReorderQuantityAtomic sql.NullInt64
}

func (q *Queries) ListLowStockItems(ctx context.Context, limitCount int64) ([]ListLowStockItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLowStockItems, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLowStockItemsRow{}
	for rows.Next() {
		var i ListLowStockItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
			&i.ReorderQuantityAtomic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionByRecipeProduct = `-- name: ListProductionByRecipeProduct :many
WITH active_production_runs AS (
    SELECT
        document.id AS document_id,
        recipe.id AS recipe_id,
        recipe.name AS recipe_name,
        output_item.id AS item_id,
        output_item.name AS item_name,
        output_item.base_unit_code,
        output_line.quantity_atomic AS actual_yield_atomic,
        output_line.inventory_value_micro AS output_inventory_value_micro,
        run.direct_production_cost_micro,
        revision.standard_yield_quantity_atomic
    FROM stock_documents document
    JOIN production_runs run ON run.document_id = document.id
    JOIN recipe_revisions revision ON revision.id = run.recipe_revision_id
    JOIN recipes recipe ON recipe.id = revision.recipe_id
    JOIN stock_document_lines output_line ON output_line.id = run.output_line_id
    JOIN items output_item ON output_item.id = output_line.item_id
    WHERE document.kind = 'PRODUCTION'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    recipe_id,
    recipe_name,
    item_id,
    item_name,
    base_unit_code,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(actual_yield_atomic), 0) AS INTEGER) AS actual_yield_atomic,
    CAST(COALESCE(SUM(output_inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro,
    CAST(COALESCE(SUM(direct_production_cost_micro), 0) AS INTEGER) AS direct_cost_micro,
    CAST(COALESCE(SUM(standard_yield_quantity_atomic), 0) AS INTEGER) AS standard_yield_atomic,
    CAST(
        COALESCE(SUM(actual_yield_atomic), 0)
        - COALESCE(SUM(standard_yield_quantity_atomic), 0)
        AS INTEGER
    ) AS variance_atomic
FROM active_production_runs
GROUP BY recipe_id, recipe_name, item_id, item_name, base_unit_code
ORDER BY actual_yield_atomic DESC, inventory_value_micro DESC, recipe_name, recipe_id
LIMIT ?1
`

type ListProductionByRecipeProductParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListProductionByRecipeProductRow struct {
	RecipeID            int64
	RecipeName          string
	ItemID              int64
	ItemName            string
	BaseUnitCode        string
	DocumentCount       int64
	ActualYieldAtomic   int64
	InventoryValueMicro int64
	DirectCostMicro     int64
	StandardYieldAtomic int64
	VarianceAtomic      int64
}

func (q *Queries) ListProductionByRecipeProduct(ctx context.Context, arg ListProductionByRecipeProductParams) ([]ListProductionByRecipeProductRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductionByRecipeProduct, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionByRecipeProductRow{}
	for rows.Next() {
		var i ListProductionByRecipeProductRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.RecipeName,
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.DocumentCount,
			&i.ActualYieldAtomic,
			&i.InventoryValueMicro,
			&i.DirectCostMicro,
			&i.StandardYieldAtomic,
			&i.VarianceAtomic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionDirectCostSeries = `-- name: ListProductionDirectCostSeries :many
WITH active_production_runs AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        output_line.quantity_atomic AS actual_yield_atomic,
        output_line.inventory_value_micro AS output_inventory_value_micro,
        run.direct_production_cost_micro
    FROM stock_documents document
    JOIN production_runs run ON run.document_id = document.id
    JOIN stock_document_lines output_line ON output_line.id = run.output_line_id
    WHERE document.kind = 'PRODUCTION'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(actual_yield_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(output_inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro,
    CAST(COALESCE(SUM(direct_production_cost_micro), 0) AS INTEGER) AS direct_cost_micro
FROM active_production_runs
GROUP BY bucket
ORDER BY bucket
`

type ListProductionDirectCostSeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListProductionDirectCostSeriesRow struct {
	Bucket              string
	Label               string
	DocumentCount       int64
	QuantityAtomic      int64
	InventoryValueMicro int64
	DirectCostMicro     int64
}

func (q *Queries) ListProductionDirectCostSeries(ctx context.Context, arg ListProductionDirectCostSeriesParams) ([]ListProductionDirectCostSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductionDirectCostSeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionDirectCostSeriesRow{}
	for rows.Next() {
		var i ListProductionDirectCostSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.DocumentCount,
			&i.QuantityAtomic,
			&i.InventoryValueMicro,
			&i.DirectCostMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductionYieldVariance = `-- name: ListProductionYieldVariance :many
WITH active_production_runs AS (
    SELECT
        document.id AS document_id,
        recipe.id AS recipe_id,
        recipe.name AS recipe_name,
        output_item.id AS item_id,
        output_item.name AS item_name,
        output_item.base_unit_code,
        output_line.quantity_atomic AS actual_yield_atomic,
        output_line.inventory_value_micro AS output_inventory_value_micro,
        run.direct_production_cost_micro,
        revision.standard_yield_quantity_atomic
    FROM stock_documents document
    JOIN production_runs run ON run.document_id = document.id
    JOIN recipe_revisions revision ON revision.id = run.recipe_revision_id
    JOIN recipes recipe ON recipe.id = revision.recipe_id
    JOIN stock_document_lines output_line ON output_line.id = run.output_line_id
    JOIN items output_item ON output_item.id = output_line.item_id
    WHERE document.kind = 'PRODUCTION'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    recipe_id,
    recipe_name,
    item_id,
    item_name,
    base_unit_code,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(standard_yield_quantity_atomic), 0) AS INTEGER) AS standard_yield_atomic,
    CAST(COALESCE(SUM(actual_yield_atomic), 0) AS INTEGER) AS actual_yield_atomic,
    CAST(
        COALESCE(SUM(actual_yield_atomic), 0)
        - COALESCE(SUM(standard_yield_quantity_atomic), 0)
        AS INTEGER
    ) AS variance_atomic,
    CAST(COALESCE(SUM(output_inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro,
    CAST(COALESCE(SUM(direct_production_cost_micro), 0) AS INTEGER) AS direct_cost_micro
FROM active_production_runs
GROUP BY recipe_id, recipe_name, item_id, item_name, base_unit_code
ORDER BY ABS(variance_atomic) DESC, recipe_name, recipe_id
LIMIT ?1
`

type ListProductionYieldVarianceParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListProductionYieldVarianceRow struct {
	RecipeID            int64
	RecipeName          string
	ItemID              int64
	ItemName            string
	BaseUnitCode        string
	DocumentCount       int64
	StandardYieldAtomic int64
	ActualYieldAtomic   int64
	VarianceAtomic      int64
	InventoryValueMicro int64
	DirectCostMicro     int64
}

func (q *Queries) ListProductionYieldVariance(ctx context.Context, arg ListProductionYieldVarianceParams) ([]ListProductionYieldVarianceRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductionYieldVariance, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductionYieldVarianceRow{}
	for rows.Next() {
		var i ListProductionYieldVarianceRow
		if err := rows.Scan(
			&i.RecipeID,
			&i.RecipeName,
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.DocumentCount,
			&i.StandardYieldAtomic,
			&i.ActualYieldAtomic,
			&i.VarianceAtomic,
			&i.InventoryValueMicro,
			&i.DirectCostMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseSpendSeries = `-- name: ListPurchaseSpendSeries :many
WITH active_purchase_lines AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'PURCHASE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS spend_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS inventory_value_micro
FROM active_purchase_lines
GROUP BY bucket
ORDER BY bucket
`

type ListPurchaseSpendSeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListPurchaseSpendSeriesRow struct {
	Bucket              string
	Label               string
	DocumentCount       int64
	QuantityAtomic      int64
	SpendMinor          int64
	InventoryValueMicro int64
}

func (q *Queries) ListPurchaseSpendSeries(ctx context.Context, arg ListPurchaseSpendSeriesParams) ([]ListPurchaseSpendSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPurchaseSpendSeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseSpendSeriesRow{}
	for rows.Next() {
		var i ListPurchaseSpendSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.DocumentCount,
			&i.QuantityAtomic,
			&i.SpendMinor,
			&i.InventoryValueMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByCustomer = `-- name: ListSalesByCustomer :many
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        document.counterparty_id,
        counterparty.name AS counterparty_name,
        line.commercial_total_minor
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN counterparties counterparty ON counterparty.id = document.counterparty_id
    WHERE document.kind = 'SALE'
      AND document.counterparty_id IS NOT NULL
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    counterparty_id,
    counterparty_name,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor
FROM active_sale_lines
GROUP BY counterparty_id, counterparty_name
ORDER BY revenue_minor DESC, document_count DESC, counterparty_name, counterparty_id
LIMIT ?1
`

type ListSalesByCustomerParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListSalesByCustomerRow struct {
	CounterpartyID   sql.NullInt64
	CounterpartyName string
	DocumentCount    int64
	RevenueMinor     int64
}

func (q *Queries) ListSalesByCustomer(ctx context.Context, arg ListSalesByCustomerParams) ([]ListSalesByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSalesByCustomer, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesByCustomerRow{}
	for rows.Next() {
		var i ListSalesByCustomerRow
		if err := rows.Scan(
			&i.CounterpartyID,
			&i.CounterpartyName,
			&i.DocumentCount,
			&i.RevenueMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesRevenueSeries = `-- name: ListSalesRevenueSeries :many
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS sales_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY bucket
ORDER BY bucket
`

type ListSalesRevenueSeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListSalesRevenueSeriesRow struct {
	Bucket         string
	Label          string
	SalesCount     int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListSalesRevenueSeries(ctx context.Context, arg ListSalesRevenueSeriesParams) ([]ListSalesRevenueSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSalesRevenueSeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRevenueSeriesRow{}
	for rows.Next() {
		var i ListSalesRevenueSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.SalesCount,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSalesProductsByQuantity = `-- name: ListTopSalesProductsByQuantity :many
WITH active_sale_lines AS (
    SELECT
        line.item_id,
        item.name AS item_name,
        item.base_unit_code,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN items item ON item.id = line.item_id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    item_id,
    item_name,
    base_unit_code,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY item_id, item_name, base_unit_code
ORDER BY quantity_atomic DESC, revenue_minor DESC, item_name, item_id
LIMIT ?1
`

type ListTopSalesProductsByQuantityParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListTopSalesProductsByQuantityRow struct {
	ItemID         int64
	ItemName       string
	BaseUnitCode   string
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListTopSalesProductsByQuantity(ctx context.Context, arg ListTopSalesProductsByQuantityParams) ([]ListTopSalesProductsByQuantityRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSalesProductsByQuantity, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopSalesProductsByQuantityRow{}
	for rows.Next() {
		var i ListTopSalesProductsByQuantityRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSalesProductsByRevenue = `-- name: ListTopSalesProductsByRevenue :many
WITH active_sale_lines AS (
    SELECT
        line.item_id,
        item.name AS item_name,
        item.base_unit_code,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN items item ON item.id = line.item_id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    item_id,
    item_name,
    base_unit_code,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY item_id, item_name, base_unit_code
ORDER BY revenue_minor DESC, quantity_atomic DESC, item_name, item_id
LIMIT ?1
`

type ListTopSalesProductsByRevenueParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListTopSalesProductsByRevenueRow struct {
	ItemID         int64
	ItemName       string
	BaseUnitCode   string
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListTopSalesProductsByRevenue(ctx context.Context, arg ListTopSalesProductsByRevenueParams) ([]ListTopSalesProductsByRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSalesProductsByRevenue, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopSalesProductsByRevenueRow{}
	for rows.Next() {
		var i ListTopSalesProductsByRevenueRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSuppliersBySpend = `-- name: ListTopSuppliersBySpend :many
WITH active_purchase_lines AS (
    SELECT
        document.id AS document_id,
        document.counterparty_id,
        counterparty.name AS counterparty_name,
        line.commercial_total_minor
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN counterparties counterparty ON counterparty.id = document.counterparty_id
    WHERE document.kind = 'PURCHASE'
      AND document.counterparty_id IS NOT NULL
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    counterparty_id,
    counterparty_name,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS spend_minor
FROM active_purchase_lines
GROUP BY counterparty_id, counterparty_name
ORDER BY spend_minor DESC, document_count DESC, counterparty_name, counterparty_id
LIMIT ?1
`

type ListTopSuppliersBySpendParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListTopSuppliersBySpendRow struct {
	CounterpartyID   sql.NullInt64
	CounterpartyName string
	DocumentCount    int64
	SpendMinor       int64
}

func (q *Queries) ListTopSuppliersBySpend(ctx context.Context, arg ListTopSuppliersBySpendParams) ([]ListTopSuppliersBySpendRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSuppliersBySpend, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopSuppliersBySpendRow{}
	for rows.Next() {
		var i ListTopSuppliersBySpendRow
		if err := rows.Scan(
			&i.CounterpartyID,
			&i.CounterpartyName,
			&i.DocumentCount,
			&i.SpendMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
