// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getAnonymousSalesTotals = `-- name: GetAnonymousSalesTotals :one
WITH anonymous_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.commercial_total_minor
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.counterparty_id IS NULL
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor
FROM anonymous_sale_lines
`

type GetAnonymousSalesTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetAnonymousSalesTotalsRow struct {
	DocumentCount int64
	RevenueMinor  int64
}

func (q *Queries) GetAnonymousSalesTotals(ctx context.Context, arg GetAnonymousSalesTotalsParams) (GetAnonymousSalesTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getAnonymousSalesTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetAnonymousSalesTotalsRow
	err := row.Scan(&i.DocumentCount, &i.RevenueMinor)
	return i, err
}

const getFreeSalesTotals = `-- name: GetFreeSalesTotals :one
WITH free_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.reason_code IN ('PROMOTION', 'SAMPLE')
      AND line.commercial_total_minor = 0
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM free_sale_lines
`

type GetFreeSalesTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetFreeSalesTotalsRow struct {
	DocumentCount  int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) GetFreeSalesTotals(ctx context.Context, arg GetFreeSalesTotalsParams) (GetFreeSalesTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getFreeSalesTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetFreeSalesTotalsRow
	err := row.Scan(
		&i.DocumentCount,
		&i.QuantityAtomic,
		&i.RevenueMinor,
		&i.CogsMicro,
	)
	return i, err
}

const getReportingCurrency = `-- name: GetReportingCurrency :one
SELECT currency_code, currency_minor_digits
FROM app_settings
WHERE id = 1
`

type GetReportingCurrencyRow struct {
	CurrencyCode        string
	CurrencyMinorDigits int64
}

func (q *Queries) GetReportingCurrency(ctx context.Context) (GetReportingCurrencyRow, error) {
	row := q.db.QueryRowContext(ctx, getReportingCurrency)
	var i GetReportingCurrencyRow
	err := row.Scan(&i.CurrencyCode, &i.CurrencyMinorDigits)
	return i, err
}

const getSalesReportTotals = `-- name: GetSalesReportTotals :one
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?1 AS TEXT)
      AND document.occurred_on <= CAST(?2 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS sales_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
`

type GetSalesReportTotalsParams struct {
	FromOccurredOn string
	ToOccurredOn   string
}

type GetSalesReportTotalsRow struct {
	SalesCount     int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) GetSalesReportTotals(ctx context.Context, arg GetSalesReportTotalsParams) (GetSalesReportTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getSalesReportTotals, arg.FromOccurredOn, arg.ToOccurredOn)
	var i GetSalesReportTotalsRow
	err := row.Scan(
		&i.SalesCount,
		&i.QuantityAtomic,
		&i.RevenueMinor,
		&i.CogsMicro,
	)
	return i, err
}

const listSalesByCustomer = `-- name: ListSalesByCustomer :many
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        document.counterparty_id,
        counterparty.name AS counterparty_name,
        line.commercial_total_minor
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN counterparties counterparty ON counterparty.id = document.counterparty_id
    WHERE document.kind = 'SALE'
      AND document.counterparty_id IS NOT NULL
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    counterparty_id,
    counterparty_name,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS document_count,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor
FROM active_sale_lines
GROUP BY counterparty_id, counterparty_name
ORDER BY revenue_minor DESC, document_count DESC, counterparty_name, counterparty_id
LIMIT ?1
`

type ListSalesByCustomerParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListSalesByCustomerRow struct {
	CounterpartyID   sql.NullInt64
	CounterpartyName string
	DocumentCount    int64
	RevenueMinor     int64
}

func (q *Queries) ListSalesByCustomer(ctx context.Context, arg ListSalesByCustomerParams) ([]ListSalesByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSalesByCustomer, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesByCustomerRow{}
	for rows.Next() {
		var i ListSalesByCustomerRow
		if err := rows.Scan(
			&i.CounterpartyID,
			&i.CounterpartyName,
			&i.DocumentCount,
			&i.RevenueMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesRevenueSeries = `-- name: ListSalesRevenueSeries :many
WITH active_sale_lines AS (
    SELECT
        document.id AS document_id,
        CAST(
            CASE
                WHEN CAST(?1 AS TEXT) = 'DAY'
                    THEN document.occurred_on
                ELSE substr(document.occurred_on, 1, 7)
            END AS TEXT
        ) AS bucket,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    CAST(bucket AS TEXT) AS bucket,
    CAST(bucket AS TEXT) AS label,
    CAST(COUNT(DISTINCT document_id) AS INTEGER) AS sales_count,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY bucket
ORDER BY bucket
`

type ListSalesRevenueSeriesParams struct {
	Granularity    string
	FromOccurredOn string
	ToOccurredOn   string
}

type ListSalesRevenueSeriesRow struct {
	Bucket         string
	Label          string
	SalesCount     int64
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListSalesRevenueSeries(ctx context.Context, arg ListSalesRevenueSeriesParams) ([]ListSalesRevenueSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSalesRevenueSeries, arg.Granularity, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRevenueSeriesRow{}
	for rows.Next() {
		var i ListSalesRevenueSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Label,
			&i.SalesCount,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSalesProductsByQuantity = `-- name: ListTopSalesProductsByQuantity :many
WITH active_sale_lines AS (
    SELECT
        line.item_id,
        item.name AS item_name,
        item.base_unit_code,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN items item ON item.id = line.item_id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    item_id,
    item_name,
    base_unit_code,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY item_id, item_name, base_unit_code
ORDER BY quantity_atomic DESC, revenue_minor DESC, item_name, item_id
LIMIT ?1
`

type ListTopSalesProductsByQuantityParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListTopSalesProductsByQuantityRow struct {
	ItemID         int64
	ItemName       string
	BaseUnitCode   string
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListTopSalesProductsByQuantity(ctx context.Context, arg ListTopSalesProductsByQuantityParams) ([]ListTopSalesProductsByQuantityRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSalesProductsByQuantity, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopSalesProductsByQuantityRow{}
	for rows.Next() {
		var i ListTopSalesProductsByQuantityRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopSalesProductsByRevenue = `-- name: ListTopSalesProductsByRevenue :many
WITH active_sale_lines AS (
    SELECT
        line.item_id,
        item.name AS item_name,
        item.base_unit_code,
        line.quantity_atomic,
        line.commercial_total_minor,
        line.inventory_value_micro
    FROM stock_documents document
    JOIN stock_document_lines line ON line.document_id = document.id
    JOIN items item ON item.id = line.item_id
    WHERE document.kind = 'SALE'
      AND document.occurred_on >= CAST(?2 AS TEXT)
      AND document.occurred_on <= CAST(?3 AS TEXT)
      AND NOT EXISTS (
          SELECT 1
          FROM stock_documents reversal
          WHERE reversal.kind = 'REVERSAL'
            AND reversal.reverses_document_id = document.id
      )
)
SELECT
    item_id,
    item_name,
    base_unit_code,
    CAST(COALESCE(SUM(quantity_atomic), 0) AS INTEGER) AS quantity_atomic,
    CAST(COALESCE(SUM(commercial_total_minor), 0) AS INTEGER) AS revenue_minor,
    CAST(COALESCE(SUM(inventory_value_micro), 0) AS INTEGER) AS cogs_micro
FROM active_sale_lines
GROUP BY item_id, item_name, base_unit_code
ORDER BY revenue_minor DESC, quantity_atomic DESC, item_name, item_id
LIMIT ?1
`

type ListTopSalesProductsByRevenueParams struct {
	LimitCount     int64
	FromOccurredOn string
	ToOccurredOn   string
}

type ListTopSalesProductsByRevenueRow struct {
	ItemID         int64
	ItemName       string
	BaseUnitCode   string
	QuantityAtomic int64
	RevenueMinor   int64
	CogsMicro      int64
}

func (q *Queries) ListTopSalesProductsByRevenue(ctx context.Context, arg ListTopSalesProductsByRevenueParams) ([]ListTopSalesProductsByRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, listTopSalesProductsByRevenue, arg.LimitCount, arg.FromOccurredOn, arg.ToOccurredOn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopSalesProductsByRevenueRow{}
	for rows.Next() {
		var i ListTopSalesProductsByRevenueRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemName,
			&i.BaseUnitCode,
			&i.QuantityAtomic,
			&i.RevenueMinor,
			&i.CogsMicro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
