// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT
    id,
    business_name,
    locale_code,
    timezone_name,
    currency_code,
    currency_minor_digits,
    hourly_labor_cost_minor,
    default_gross_margin_basis_points,
    created_at_ms,
    updated_at_ms
FROM app_settings
WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.LocaleCode,
		&i.TimezoneName,
		&i.CurrencyCode,
		&i.CurrencyMinorDigits,
		&i.HourlyLaborCostMinor,
		&i.DefaultGrossMarginBasisPoints,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const getMeasurementUnit = `-- name: GetMeasurementUnit :one
SELECT
    code,
    name,
    symbol,
    dimension,
    atomic_numerator,
    atomic_denominator,
    is_item_base,
    is_seeded
FROM measurement_units
WHERE code = ?1
`

func (q *Queries) GetMeasurementUnit(ctx context.Context, code string) (MeasurementUnit, error) {
	row := q.db.QueryRowContext(ctx, getMeasurementUnit, code)
	var i MeasurementUnit
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Dimension,
		&i.AtomicNumerator,
		&i.AtomicDenominator,
		&i.IsItemBase,
		&i.IsSeeded,
	)
	return i, err
}

const listMeasurementUnits = `-- name: ListMeasurementUnits :many
SELECT
    code,
    name,
    symbol,
    dimension,
    atomic_numerator,
    atomic_denominator,
    is_item_base,
    is_seeded
FROM measurement_units
ORDER BY
    CASE dimension
        WHEN 'MASS' THEN 1
        WHEN 'VOLUME' THEN 2
        WHEN 'COUNT' THEN 3
    END,
    atomic_numerator,
    atomic_denominator,
    code
`

func (q *Queries) ListMeasurementUnits(ctx context.Context) ([]MeasurementUnit, error) {
	rows, err := q.db.QueryContext(ctx, listMeasurementUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MeasurementUnit{}
	for rows.Next() {
		var i MeasurementUnit
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Dimension,
			&i.AtomicNumerator,
			&i.AtomicDenominator,
			&i.IsItemBase,
			&i.IsSeeded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppSettings = `-- name: UpdateAppSettings :one
UPDATE app_settings
SET
    business_name = ?1,
    locale_code = ?2,
    timezone_name = ?3,
    currency_code = ?4,
    currency_minor_digits = ?5,
    hourly_labor_cost_minor = ?6,
    default_gross_margin_basis_points = ?7,
    updated_at_ms = ?8
WHERE id = 1
  AND updated_at_ms = ?9
RETURNING
    id,
    business_name,
    locale_code,
    timezone_name,
    currency_code,
    currency_minor_digits,
    hourly_labor_cost_minor,
    default_gross_margin_basis_points,
    created_at_ms,
    updated_at_ms
`

type UpdateAppSettingsParams struct {
	BusinessName                  string
	LocaleCode                    string
	TimezoneName                  string
	CurrencyCode                  string
	CurrencyMinorDigits           int64
	HourlyLaborCostMinor          sql.NullInt64
	DefaultGrossMarginBasisPoints sql.NullInt64
	UpdatedAtMs                   int64
	ExpectedUpdatedAtMs           int64
}

func (q *Queries) UpdateAppSettings(ctx context.Context, arg UpdateAppSettingsParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updateAppSettings,
		arg.BusinessName,
		arg.LocaleCode,
		arg.TimezoneName,
		arg.CurrencyCode,
		arg.CurrencyMinorDigits,
		arg.HourlyLaborCostMinor,
		arg.DefaultGrossMarginBasisPoints,
		arg.UpdatedAtMs,
		arg.ExpectedUpdatedAtMs,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.LocaleCode,
		&i.TimezoneName,
		&i.CurrencyCode,
		&i.CurrencyMinorDigits,
		&i.HourlyLaborCostMinor,
		&i.DefaultGrossMarginBasisPoints,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}
