// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateBatch(arg1:string,arg2:number,arg3:number):Promise<main.InventoryBatchDTO>;

export function DeleteBatch(arg1:string):Promise<void>;

export function GetBatch(arg1:string):Promise<main.InventoryBatchDTO>;

export function GetBatchesByItem(arg1:string):Promise<Array<main.InventoryBatchDTO>>;

export function UpdateBatchQuantity(arg1:string,arg2:number):Promise<void>;
