// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBatch(arg1, arg2, arg3) {
  return window['go']['main']['BatchService']['CreateBatch'](arg1, arg2, arg3);
}

export function DeleteBatch(arg1) {
  return window['go']['main']['BatchService']['DeleteBatch'](arg1);
}

export function GetBatch(arg1) {
  return window['go']['main']['BatchService']['GetBatch'](arg1);
}

export function GetBatchesByItem(arg1) {
  return window['go']['main']['BatchService']['GetBatchesByItem'](arg1);
}

export function UpdateBatchQuantity(arg1, arg2) {
  return window['go']['main']['BatchService']['UpdateBatchQuantity'](arg1, arg2);
}
