// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateItem(arg1, arg2, arg3) {
  return window['go']['main']['ItemService']['CreateItem'](arg1, arg2, arg3);
}

export function DeleteItem(arg1) {
  return window['go']['main']['ItemService']['DeleteItem'](arg1);
}

export function GetAllItems() {
  return window['go']['main']['ItemService']['GetAllItems']();
}

export function GetItem(arg1) {
  return window['go']['main']['ItemService']['GetItem'](arg1);
}

export function UpdateItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ItemService']['UpdateItem'](arg1, arg2, arg3, arg4);
}
