// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateItem(arg1:string,arg2:string,arg3:number):Promise<main.ItemDTO>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetAllItems():Promise<Array<main.ItemDTO>>;

export function GetItem(arg1:string):Promise<main.ItemDTO>;

export function UpdateItem(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;
