// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProduct(arg1, arg2, arg3, arg4) {
  return window['go']['main']['ProductService']['CreateProduct'](arg1, arg2, arg3, arg4);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['ProductService']['DeleteProduct'](arg1);
}

export function GetAllProducts() {
  return window['go']['main']['ProductService']['GetAllProducts']();
}

export function GetProduct(arg1) {
  return window['go']['main']['ProductService']['GetProduct'](arg1);
}
