// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddIngredient(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CreateRecipe(arg1:string,arg2:number):Promise<main.RecipeDTO>;

export function DeleteRecipe(arg1:string):Promise<void>;

export function GetAllRecipes():Promise<Array<main.RecipeDTO>>;

export function GetIngredients(arg1:string):Promise<Array<main.RecipeIngredient>>;

export function GetRecipe(arg1:string):Promise<main.RecipeDTO>;

export function RemoveIngredient(arg1:string,arg2:string):Promise<void>;

export function UpdateRecipe(arg1:string,arg2:string,arg3:number):Promise<void>;
