// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIngredient(arg1, arg2, arg3) {
  return window['go']['main']['RecipeService']['AddIngredient'](arg1, arg2, arg3);
}

export function CreateRecipe(arg1, arg2) {
  return window['go']['main']['RecipeService']['CreateRecipe'](arg1, arg2);
}

export function DeleteRecipe(arg1) {
  return window['go']['main']['RecipeService']['DeleteRecipe'](arg1);
}

export function GetAllRecipes() {
  return window['go']['main']['RecipeService']['GetAllRecipes']();
}

export function GetIngredients(arg1) {
  return window['go']['main']['RecipeService']['GetIngredients'](arg1);
}

export function GetRecipe(arg1) {
  return window['go']['main']['RecipeService']['GetRecipe'](arg1);
}

export function RemoveIngredient(arg1, arg2) {
  return window['go']['main']['RecipeService']['RemoveIngredient'](arg1, arg2);
}

export function UpdateRecipe(arg1, arg2, arg3) {
  return window['go']['main']['RecipeService']['UpdateRecipe'](arg1, arg2, arg3);
}
