// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateSale(arg1:string,arg2:number,arg3:number):Promise<main.SaleDTO>;

export function DeleteSale(arg1:string):Promise<void>;

export function GetAllSales():Promise<Array<main.SaleDTO>>;

export function GetSale(arg1:string):Promise<main.SaleDTO>;
