// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSale(arg1, arg2, arg3) {
  return window['go']['main']['SaleService']['CreateSale'](arg1, arg2, arg3);
}

export function DeleteSale(arg1) {
  return window['go']['main']['SaleService']['DeleteSale'](arg1);
}

export function GetAllSales() {
  return window['go']['main']['SaleService']['GetAllSales']();
}

export function GetSale(arg1) {
  return window['go']['main']['SaleService']['GetSale'](arg1);
}
