// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['UserService']['ActivateLicense'](arg1);
}

export function GetUserStatus() {
  return window['go']['main']['UserService']['GetUserStatus']();
}

export function SaveUserData(arg1, arg2) {
  return window['go']['main']['UserService']['SaveUserData'](arg1, arg2);
}

export function UpdateUserData(arg1, arg2, arg3) {
  return window['go']['main']['UserService']['UpdateUserData'](arg1, arg2, arg3);
}
