// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1:string):Promise<boolean>;

export function GetUserStatus():Promise<boolean>;

export function SaveUserData(arg1:string,arg2:string):Promise<void>;

export function UpdateUserData(arg1:string,arg2:boolean,arg3:string):Promise<void>;
